### PR TITLE
Feat: Added contact messages delete feature for admin successfully issue 575

### LINKED ISSUE #575: [Feature Request]: Adding delete messages feature for received contact messages by admin
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In future, If admin gets 1K+ messages, it will be headache that's why the admin will delete the messages which is not that important or spam messages.

### Use Case

Admin enhancment

### Benefits

Admin feature improvement

### Add ScreenShots

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [ #575 ]

### Description

1. In backend, I created a route and controller for creating the delete message feature.
2. In admin, I created the button delete in which i am calling the api for deleting the message.
3. The design is responsive.

### Related Issues
Fixes #575 

### Changes Made
New feature: Added contact messages delete feature for admin.

### Screenshots

image

### Video

https://github.com/user-attachments/assets/d8c18f10-2f4f-4341-a79e-c7305c42d9c1

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Review by VaibhavArora314 — APPROVED** [review]

**Review by akbatra567 — APPROVED** [review]

**Comment by MeetDOD** [comment]
@VaibhavArora314 Give level also.

when you review you give level their only 👍

**Comment by MeetDOD** [comment]
@VaibhavArora314 @akbatra567  had given level to other pr which he merge but didn't given to my pr I don't why he is doing/acting like that I also don't care about him only 2 days is remaing he will his way and me on my way.

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 @akbatra567  had given level to other pr which he merge but didn't given to my pr I don't why he is doing/acting like that I also don't care about him only 2 days is remaing he will his way and me on my way.  

I already gave the label and mistakes happen. Don't need to react this way.

**Comment by MeetDOD** [comment]
> > @VaibhavArora314 @akbatra567  had given level to other pr which he merge but didn't given to my pr I don't why he is doing/acting like that I also don't care about him only 2 days is remaing he will his way and me on my way.
> 
> I already gave the label and mistakes happen. Don't need to react this way.

Bro if happen one time its okay but doing for me is an exception, I don't know why ?

**Comment by MeetDOD** [comment]
let it be never mind !

**Pull request merged**
