### PR TITLE
Added Rateus Option

### PR DESCRIPTION
**Pull request by sailaja-adapa**
Hello Project Admin
I Added Rate us option - Solved #312 
Kindly please go through this PR @VaibhavArora314 @manikumarreddyu 

https://github.com/VaibhavArora314/StyleShare/assets/161804629/899912a5-3a08-49fc-a55f-22ab9fc0030e

### CODE REVIEW

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
remove package-lock from root of repo

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by manikumarreddyu** [comment]
image


hey @VaibhavArora314  @sailaja-adapa  @Ultimateutkarsh11 see this

**Comment by VaibhavArora314** [comment]
> image image image
> hey @VaibhavArora314 @sailaja-adapa @Ultimateutkarsh11 see this

thanks @manikumarreddyu for pointing this out
@sailaja-adapa please also resolve this

**Comment by sailaja-adapa** [comment]
yeah okk @manikumarreddyu @VaibhavArora314

**Comment by sailaja-adapa** [comment]
@VaibhavArora314 is it okay now??

mob

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 is it okay now??
> 
> mob

see live website for reference

**Comment by VaibhavArora314** [comment]
@sailaja-adapa any updates?

**Comment by sailaja-adapa** [comment]
@VaibhavArora314 I almost done. On small screen when I try to open menu,language selector is colliding with menu option it's a small issue I will solve and update you

**Comment by sailaja-adapa** [comment]
@VaibhavArora314 Kindly go through this PR and see if still issue exists

mobicons

**Pull request closed without merging**
