### PR TITLE
Feat: Added lazy loading for cards and loader for tables in admin panel successfully issue 438

### LINKED ISSUE #438: [Feature Request]: Adding loader / lazy loading in the whole admin panel
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

1. For the status card i will aplly lazy loading.
2. For the table i will apply loader.

I will enhance the admin panel.

### Use Case

UI/UX

### Benefits

Enhancement

### Add ScreenShots

Card lazy loading:

image

Table loader:

image

Note: I will you this loader instead of the default loader created on the style share, also i will change the color to match the theme.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [#438 ]

### Description

1. With help of react skeleton loader I had applied the lazy loading in Status cards of admin.
2. With the help of react spinners I had applied the Circle ring loader in all the tables.
3.  The design is responsive.

### Related Issues
Fixes #438 

### Changes Made
New features: Added lazy loading for cards and loader for tables in admin panel.

### Screenshots

image

### Video

https://github.com/user-attachments/assets/fe833f6b-29ae-45f4-8cdc-856f09cbe930

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
Also add a loader for stats page since initially graphs are empty

**Comment by MeetDOD** [comment]
> Also add a loader for stats page since initially graphs are empty

Done 👍

**Review by akbatra567 — APPROVED** [review]

**Review by Ultimateutkarsh11 — APPROVED** [review]
@MeetDOD kindly resolve the merge conflicts, rest looks good

**Comment by MeetDOD** [comment]
> @MeetDOD kindly resolve the merge conflicts, rest looks good

Done 👍

**Comment by MeetDOD** [comment]
@Ultimateutkarsh11 see the efforts for finding this libraries and choosing the correct design and you are giving it LEVEL1 🗿 bruh ! Can you increase the level if possible ?

**Comment by MeetDOD** [comment]
> @Ultimateutkarsh11 see the efforts for finding this libraries and choosing the correct design and you are giving it LEVEL1 🗿 bruh ! Can you increase the level if possible ?

@VaibhavArora314

**Pull request merged**
