### PR TITLE
Bug: Modified the whole navbar and adjust the google translator button successfully issue 462

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [#462 ]

### Description

1.  I Changed the whole navbar and specially the added the user image and below it there is a dropdown like most of the webapps have nowadays.
2.  The design is responsive in all the devices and can work in both light/dark mode.
3.  Removed the white space also.
4.  Add google translator in fixed positon.
5.  If added in navbar it will lead to problem.

### Changes Made
Bug fixes: Modified the whole navbar and adjust the google translator button. 

### Screenshots

image

image

image

image

image

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
Looking good but after login I am still seeing options of signin and signup in mobile view
image

**Comment by MeetDOD** [comment]
> Looking good but after login I am still seeing options of signin and signup in mobile view image

OOPs I forgot to add that isLogged in condition, I will fix it 👍

**Comment by MeetDOD** [comment]
@VaibhavArora314 check now 😀

**Review by VaibhavArora314 — APPROVED** [review]

**Review by akbatra567 — APPROVED** [review]

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by MeetDOD** [comment]
@Ultimateutkarsh11 please add level 2 because I have to do navbar from scratch that's why !

**Comment by MeetDOD** [comment]
@VaibhavArora314

**Pull request merged**
