### PR TITLE
Feat/footer UI

### LINKED ISSUE #128: [Feature Request]: UI of the footer
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

UI of the footer is not looking good. 

### Use Case

I want to make the betterment of the UI of the footer . Now it looks not properly organised. 

### Benefits

It will make the footer look better that will match with the overall UI of the site.

### Add ScreenShots

_No response_

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by anwesha2002**
# Pull Request

### Title
Changed the UI of the footer
### Description
This PR changes the UI of the footer and aligns everything

### Related Issues
Fixes #128 

### Changes Made
1. added a newsletter
2. added leaderboard link to the quick link
3. aligned and stylised the footer

### Checklist 

- [ x] I have tested the changes locally
- [x ] Documentation has been updated (if necessary)
- [x ] Changes are backward-compatible

### Screenshots (if applicable)
Screenshot 2024-06-16 133434

### Additional Notes

Footer

### CODE REVIEW

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
remove newsletter from footer, since we don't have such thing or any plans to implement it in the future for now

**Comment by VaibhavArora314** [comment]
image

rather than 3 things, simply write copyright part

**Comment by manikumarreddyu** [comment]
Screenshot_2024-06-17-17-12-42-588-edit_com android chrome
For mobile view it is not coming properly 
Make changes.. @anwesha2002

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
remove these from all translations since these are not used anymore
```
        "subscribe" : "Subscribe to get latest update",
        "sub_button": "Get Updated",
        "accessibility" : "Accessibility Statement",
        "conduct" : "Supplier Code of Conduct",
```

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
image

**Pull request closed without merging**
