### PR TITLE
Feat: Added Feedback/Testimonial  control in admin panel successfully issue 547

### LINKED ISSUE #547: [Feature Request]: Adding feedback control in admin panel
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In this I will fetch all the feedback from the user and admin will select only those feedback which admin like and will show on home page section of the style share.

### Use Case

Admin feature

### Benefits

Admin enhancment

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [ #547 ]

### Description

1. In backend, I created a new field in prisma as visible:false, and also created a controller and routes for the admin to get all the feedback and also updating the visiblility.
2. In Style share main page if visibility: false then no feeback is show else it will show according to admin.
3. In admin, I created a coponent name as UserFeedback in which I am fetching all the feedbacks and with button click admin can set visible:true/false respectively.
4. Also I created interface for the feedback.
5. The design is responsive.

### Related Issues
Fixes #547 

### Changes Made
New feature: Added Feedback/Testimonial  control in admin panel.

### Screenshots 

image

image

### Video

https://github.com/user-attachments/assets/86132236-87e5-429e-90be-acd88ea6a349

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by MeetDOD** [comment]
@VaibhavArora314 where @Ultimateutkarsh11 Gone ?

**Comment by Ultimateutkarsh11** [comment]
> @VaibhavArora314 where @Ultimateutkarsh11 Gone ?

As the college vacations are now over, I'm a little busy nowadays!

**Comment by MeetDOD** [comment]
@VaibhavArora314 Please give level 3 you can see the LOC and backend + frontend logic building I hope you consider my request 🙏

**Comment by MeetDOD** [comment]
> > @VaibhavArora314 where @Ultimateutkarsh11 Gone ?
> 
> As the college vacations are now over, I'm a little busy nowadays!

No problem, keep up the good work bro 👍

**Comment by MeetDOD** [comment]
> @VaibhavArora314 Please give level 3 you can see the LOC and backend + frontend logic building I hope you consider my request 🙏

@VaibhavArora314 consider this also 🙏

**Review by akbatra567 — APPROVED** [review]

**Pull request merged**
