### PR TITLE
Add Password Strength and Toggle Password

### PR DESCRIPTION
**Pull request by kushalkumar1362**
### It includes:
- Real-time password strength evaluation using the `zxcvbn` library.
- Visual indicators for password strength.
- Password suggestions with FontAwesome icons to indicate whether specific password criteria are met.
- Add Toggle password eye using `react-icons` library.

## Changes
- Updated the `PasswordInput` component to include the password strength meter.
- Added checks for lowercase & uppercase letters, numbers, special characters, and minimum length.
- Add Toggle password eye using `react-icons` library in both signup and login page.

## Screenshots
image

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

## Linked Issues: #37

### CODE REVIEW

**Comment by kushalkumar1362** [comment]
please also add labels in PR as per GSSOC guidelines

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
resolve merge conflicts, rest is good

**Comment by kushalkumar1362** [comment]
> resolve merge conflicts, rest is good

when is make request there is no conflicts let me check

**Comment by kushalkumar1362** [comment]
please merge this before merge another request this conflicts that arire because you merge some another request
also add label in the PR

**Comment by kushalkumar1362** [comment]
@VaibhavArora314

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by kushalkumar1362** [comment]
@VaibhavArora314 as per guidelines please add level label , gssoc label here

**Pull request merged**
