### PR TITLE
Feat: Created admin login / logout in frontend successfully issue 344

### LINKED ISSUE #344: [Feature Request]: Creating admin login / logout in frontend
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Sign-in dashboard for admin users with a route /sign-in. once signed in the user can see a blank page for now.
In this the frontend will do the login/logout functionality with the backend logic and then integrating with tha admin folder.

### Use Case

Admin flexibility.

### Benefits

Admin usage

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves[#344 ]

### Description

1.  Created login page for admin.
2.  Added toast for both login and logout.
3.  Modified 404 not found page.

### Related Issues
Fixes #344 

### Changes Made
New features:  Created admin login / logout in frontend.

### Screenshots

image

image

image

image

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by MeetDOD** [comment]
@VaibhavArora314 all three mentors have to review ? I thaught you are the only one. previously you were only for merging and all !

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 all three mentors have to review ? I thaught you are the only one. previously you were only for merging and all !

Previously some of them were not active or assigned, but since most of them are present now so it would be great to get reviews from each of them.

**Comment by MeetDOD** [comment]
> > @VaibhavArora314 all three mentors have to review ? I thaught you are the only one. previously you were only for merging and all !
> 
> Previously some of them were not active or assigned, but since most of them are present now so it would be great to get reviews from each of them.

Ohh I see

**Comment by MeetDOD** [comment]
@akbatra567 @Ultimateutkarsh11 can you review ASAP because their are lot more issues to cover up and also @manikumarreddyu is waiting for this admin panel so that he can raise new issues.

I hope you consider my request.
Thank You

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by VaibhavArora314** [comment]
resolve merge conflicts

**Comment by MeetDOD** [comment]
@VaibhavArora314 Done 👍

**Comment by MeetDOD** [comment]
@akbatra567 please review this pr if any changes just let me know 😀

**Review by akbatra567 — APPROVED** [review]

**Pull request merged**
