### PR TITLE
Adding copy in code editor

### PR DESCRIPTION
**Pull request by manikumarreddyu**
# Pull Request

### Title

Adding copy in code editor
### Description

Adding copy in code editor

### Related Issues

Fixed: #210 

### Changes Made

1.codeeditor.tsx

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)
image

image

### CODE REVIEW

**Comment by manikumarreddyu** [comment]
hey @VaibhavArora314 check it once , and let me know any changes required.
Thank you!!

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
image
add copy button on left of this and rather than writing copy, maybe you can use an icon for it

**Comment by manikumarreddyu** [comment]
Okay

**Comment by manikumarreddyu** [comment]
image

check it once @VaibhavArora314

**Comment by manikumarreddyu** [comment]
dont merge it wait.. @VaibhavArora314

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
