### PR TITLE
Added syntax highlighting in post

### PR DESCRIPTION
**Pull request by Joyosmit**
# Pull Request

### Title
Added syntax highlighting in the post

### Changes Made
1. Used react-syntax-highlighter for syntax highlighting
2. Changed code in Post.tsx

### Checklist 

- [x] I have tested the changes locally
- [ ] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots
AA2211

### CODE REVIEW

**Comment by Joyosmit** [comment]
Pls add the gssoc label and level1/2/3 label

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
1. remove comments from sendWelcomeMail.ts
2. remove console.log from signup

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by VaibhavArora314** [comment]
The deployment keeps failing, please check

**Comment by Joyosmit** [comment]
Is there any way to check the deployment logs of someone else?

**Comment by VaibhavArora314** [comment]
> Is there any way to check the deployment logs of someone else?

image

**Comment by Joyosmit** [comment]
Fixed the deployment issue

**Comment by VaibhavArora314** [comment]
everything is good but why code section is shown 2 times 
image

**Comment by VaibhavArora314** [comment]
ok, so the original functionality was that when preview button is pressed preview is shown then we can see code back by pressing show code
image
image

now in your changes, when preview button is pressed preview is shown separately and show code option is also shown even when code is shown
image
image

**Comment by VaibhavArora314** [comment]
in short, I want you to show a code window where syntax-highlighted code is shown, when the user clicks the preview button then code is hidden and the preview is shown. after that when the show code is pressed then code is shown again and the preview is hidden.

also delete package-lock.json from root of folder

**Comment by VaibhavArora314** [comment]
Comment axios defaulturl in app.tsx

**Comment by VaibhavArora314** [comment]
closing this pr for now due to so many merge conflicts and confusion, please raise another pr for the same

**Pull request closed without merging**
