### PR TITLE
✔️Improved the "FAQ Section" of the Website.

### LINKED ISSUE #492: ➕Enhancement: Improving the "FAQ Section" of the Website!
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @VaibhavArora314 

I would like to enhance the UI and functionality of the current FAQ page to improve user experience.

### Here's what I Will do:
- **Styling it to follow the Website's theme.**
- **Add new comprehensive questions** based on user feedback and common inquiries.
- **Adding transition moving effect to the FAQ sections questions.**
- **Improve the Alignment and Width** of the FAQ Questions and answers.
- Will add Better **Hovering effects and Smooth Transitions** to make it interactive.

**Current FAQ Section -** 
image

**For example like this - (my previous work)** 

https://github.com/user-attachments/assets/c89daa15-163c-47fb-824d-e31db4c10481

Please assign me under GSSOC'24.
Looking forward to contributing to our project!
thankyou!

### Use Case

.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by aslams2020**
Hey @VaibhavArora314 
issue closes #492 

I have improved the FAQ Section of the Website - 

### What I Did - 
1. **Improved the Styling of Both Questions and Answers Triggers.**
2. Added more **"Comprehensive Questions"** to the FAQ Page
3. Added **Text-Highlighting Shadow to the Main-Heading.**
4. **Added Hovering Effects to the Questions-trigger.**
5. **Added Hovering Effects to the Answer-trigger.**
6. **Added Hovering Effects and Text shadow** to the **"Back to Home" Button.**
7. Also, Increased the Width of the Questions.

**Here's the Before -** 
image

**Here's the Implementation -**

https://github.com/user-attachments/assets/76ee09eb-d5ec-4e03-ad80-ecee774fabaa

Please take a look.
thankyou!

### CODE REVIEW

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
Looks good just 2 changes:
1. Remove package-lock.json from root of repo
2. Don't do plain CSS styling use tailwind to maintain consistency as much as possible, try apply if u want to do in external CSS file

Same changes as your other pull request

**Comment by aslams2020** [comment]
@VaibhavArora314 Done! Please check

**Comment by aslams2020** [comment]
@akbatra567 @VaibhavArora314 Please take a look

**Review by VaibhavArora314 — APPROVED** [review]

**Review by akbatra567 — APPROVED** [review]

**Comment by aslams2020** [comment]
@VaibhavArora314 @akbatra567 If Approved. Please merge the PR
thankyou!

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Pull request merged**
