### PR TITLE
Added Icons to Navbar

### PR DESCRIPTION
**Pull request by sailaja-adapa**
Hello Project Admin
I Added Icons to Navbar - Solved #311 
Kindly Please go through this PR @VaibhavArora314 

https://github.com/VaibhavArora314/StyleShare/assets/161804629/7d06bf90-9359-4eed-87aa-ce311f938e62

### CODE REVIEW

**Comment by VaibhavArora314** [comment]
the icons added looks good, but it isn't responsive after login. maybe you can increase the breakpoint
image

**Comment by sailaja-adapa** [comment]
I will change them later and update you  @VaibhavArora314

**Comment by VaibhavArora314** [comment]
@sailaja-adapa any updates?

**Comment by sailaja-adapa** [comment]
@VaibhavArora314 I almost done. On small screen when I try to open menu,language selector is colliding with menu option it's a small issue I will solve and update you

**Pull request closed without merging**
