### PR TITLE
feat: Added customization of component by user in style share successfully Issue customize 142

### LINKED ISSUE #142: [Feature Request]: Implementing Chat App in style share
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The chat app will help user to generate tailwind components, new ideas etc...
I will use gemini api for the same.

### Use Case

AI integration

### Benefits

User experience will increase.

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [#142 ]

### Description

1. In backend: Implemented route and controller, in controller imlemented gemini api.
2. In frontend: Route to navigate from post page to customize page and posting to server and fetching from gemini api.
3. For get response user should be logged in and verified.
4.  Preview is available for both the code original + created by gemini.
5.  Added toast for almost all button click.
6.  For working in your system add your api key in .env at API_KEY=" ".
7.  For api key go to [https://ai.google.dev/aistudio](url) , sign in and then click on, 

image

 after that click on create API key
 
image

create project or just click on any existing and you good to go...

### Related Issues
Fixes #142 

### Changes Made
New features: Added customization of component by user in style share.

### Screenshots

Screenshot 2024-06-09 013210

### Video

https://github.com/VaibhavArora314/StyleShare/assets/120380073/09ce6676-998e-43d9-8501-35f19affa584

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Comment by MeetDOD** [comment]
@VaibhavArora314 It was fun to make this feature and also i learned a lot  of things because of you. So, thank you buddy 😄

**Review by VaibhavArora314 — COMMENTED** [review]
Good work, since there is a big feature so I will take some time to review it

**Comment by MeetDOD** [comment]
Sure @VaibhavArora314 No prob :)

**Comment by MeetDOD** [comment]
@VaibhavArora314 there is a conflicts should i resolved it or you will do it ?

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 there is a conflicts should i resolved it or you will do it ?

yes resolve merge conflicts

**Comment by VaibhavArora314** [comment]
hey @MeetDOD, i was viewing the deployment and saw that I was several times getting this error 
image
upon reviewing the logs, I found that the deployment has each request have a 10sec limit and the response is taking more than that causing this error
image
is there any work for this?

**Comment by MeetDOD** [comment]
i also got the same error when i pasted wrong api key

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 did you giving the api key in .env ?

Yes, I specified the api key and I am getting results also but the issue is most of the time request timeout.

**Comment by MeetDOD** [comment]
So, what should be the solution now ?

**Comment by VaibhavArora314** [comment]
> So, what should be the solution now ?

Don't worry, I am merging this for now. And will try some possible solutions to see it is possible to resolve this.

**Pull request merged**
