### PR TITLE
Added Effect in How it Works

### LINKED ISSUE #451: [Feature Request]: Add loading when scroll effects on about page's true marks
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

image

This true marks sentence load one by one when scroll down.

### Use Case

Better UI

### Benefits

Better experience.

### Add ScreenShots

NA

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by zalabhavy**
# Pull Request

### Title

Add loading when scroll effects on about page's true marks.

### Description

Added Effect like Home page right tick text in about's how it works section text.

### Related Issues

Fixes #451

### Changes Made

Added Effects in About Page

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)

https://www.loom.com/share/e07e8e5c0f9b42e1bd71d36e98c0ba39

### CODE REVIEW

**Review by VaibhavArora314 — COMMENTED** [review]
looking good, just remove react import
image

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by zalabhavy** [comment]
@VaibhavArora314 @akbatra567  React import removed !
Please check it and merge !

Thank You !

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
the animation looks good but a minor change is needed, when the items show up one by one they push the previous one up

**Comment by zalabhavy** [comment]
@VaibhavArora314 Done !
https://www.loom.com/share/52a8830b32534449bdd9be681e978bae

**Review by VaibhavArora314 — APPROVED** [review]

**Review by akbatra567 — APPROVED** [review]

**Comment by zalabhavy** [comment]
@VaibhavArora314 @Ultimateutkarsh11 @akbatra567 please also provide label !

Thank You !

**Comment by zalabhavy** [comment]
@VaibhavArora314 level2 Please !

**Pull request merged**
