### PR TITLE
Text animation

### PR DESCRIPTION
**Pull request by Rohitha-pudu**
#68 fixes

### Hero Section text animation

- [ x] I have tested the changes locally
- [ ] Documentation has been updated (if necessary)
- [ x] Changes are backward-compatible

### CODE REVIEW

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
good work just remove merge conflicts

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by VaibhavArora314** [comment]
I just noticed that for smaller devices, some of the text is hidden on the right side. Is it possible to move the extra text to next line?

**Comment by VaibhavArora314** [comment]
also resolve merge conflicts

**Comment by Rohitha-pudu** [comment]
> I just noticed that for smaller devices, some of the text is hidden on the right side. Is it possible to move the extra text to next line?

yes,i reduced the size accordingly

**Comment by VaibhavArora314** [comment]
maybe you forgot to import animation while resolving merge conflicts

image

**Comment by Rohitha-pudu** [comment]
> maybe you forgot to import animation while resolving merge conflicts
> 
> image

sorry .Is it okay now

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
