### PR TITLE
feat: Added category tags posts pages and filtered with tags successfully Issue 270

### LINKED ISSUE #270: [Feature Request]: Making separate Category for posts with their respective tags
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

So, like in e-commerce webapp there is a category eg: cloths, electronics, books, gaming etc likewise i want to create a feature such that when some one click on the tag it will navigate to the posts page with the simailar posts.
eg: when user click on navbar tag it will redirect it to the navbar page where all the posts is of navbar.

### Use Case

UX

### Benefits

UI

### Add ScreenShots

1. Implementing on Post page.

image

2. Implementing on Posts page.
3. 
image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [#270 ]

### Description

1.  Created Category API controller and routes to fetch all the tags.
2.  Created TagPosts.tsx in which routing is done when click on postcard tags as well as post tags, it will redirect user to `/post/tag/:tag` and he/she will see the post of that tag only.
3.  Changed the design of the tags and also adjust in light/dark mode.

### Related Issues
Fixes #270 

### Changes Made
New features: Added category tags posts pages and filtered with tags.

### Screenshots

image

image

image

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Comment by MeetDOD** [comment]
@VaibhavArora314 Thanks for solving usePosts error 😀

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
instead of creating a separate page maybe we can use query parameters to pass the initial tags list to usePost hook and we can update query parameter as we add or remove tags

**Comment by MeetDOD** [comment]
> also if I am not wrong the all tags route is used for displaying tags at homepage?

Yes I created the backend in this pr only and in #271 i fetched it and created frontend 👍

**Comment by MeetDOD** [comment]
> instead of creating a separate page maybe we can use query parameters to pass the initial tags list to usePost hook and we can update query parameter as we add or remove tags

So, you don't want to create the new page instead i should do it in the Postcard and posts ?

**Comment by MeetDOD** [comment]
But it should navigate to some end point some route to show the tag posts like some conditional route for navigation also in above code no extra api call is happening it is only navigating like not hitting any api, so can you explain your approach in details If you don't mind ?

**Comment by VaibhavArora314** [comment]
so basically, I was thinking that you add a tag "test" and "nav" the route becomes something like /app/posts?tags=test,nav so that tags are separated by the comma and can be split easily. In case the user clicks on a specific card tag, we can add it at this end of the URL and update the state.

**Comment by MeetDOD** [comment]
@VaibhavArora314 I got your approach but it is not applying also user click multiple times the same tag it will mess the whole url also when reload it can give page not found that's why i created a fresh route, I think that you will understand it else we can do some other methods 🙂

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 I got your approach but it is not applying also user click multiple times the same tag it will mess the whole url also when reload it can give page not found that's why i created a fresh route, I think that you will understand it else we can do some other methods 🙂

why will it give page not found? the benefit of query parameters is that the results are the same across page reloads

**Comment by MeetDOD** [comment]
@VaibhavArora314 see now i did according to what you told me, with params instead of component 🙂

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
great work, just resolve merge conflicts

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by MeetDOD** [comment]
Finally 😭 it's done, @VaibhavArora314 level 3 for one 🙂

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
