### PR TITLE
feat: Added deleting a post created by a user successfully Issue 126

### LINKED ISSUE #126: [Feature Request]: delete a post created by user.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

A user can delete there added post at anytime.
I will implement the api for delete also the routes and rest will be done by the frontend.

### Use Case

User flexibility.

### Benefits

User power.

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [#126]

### Description

1.   I created a controller for post deletion and also the routes for implementing in frontend.
2.   In frontend i used icon when press i am triggering to the api and only user itself post can be deleted, a user cannot delete others post.
3.   Also modified Read more button css.

### Related Issues
Fixes #126 

### Changes Made
New feature: Deleting a post created by a user.

### Video

https://github.com/VaibhavArora314/StyleShare/assets/120380073/859f5ec6-fbe3-4412-855a-49e9a61bc114

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Comment by MeetDOD** [comment]
@VaibhavArora314 why deployment failed ?

**Comment by VaibhavArora314** [comment]
Dont push changes of your other PR, it makes difficult for me to review.
image

**Comment by MeetDOD** [comment]
> Dont push changes of your other PR, it makes difficult for me to review. image

Okay i will fix it

**Comment by MeetDOD** [comment]
@VaibhavArora314 I got the error, the error is not showing on VS code but when you give in that file then it highlight the error, silly me. It's updated now you can merge it :)

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
