### PR TITLE
feat: Created admin login backend and frontend successfully issue 320 

### LINKED ISSUE #320: [Feature Request]: Adding login for admin
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Creating an additional parameter in the user model for isAdmin which is false for all users by default and a sign-in dashboard for admin users with a route /sign-in. once signed in the user can see a blank page for now.

### Use Case

Admin flexibility.

### Benefits

Admin usage

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [#320 ]

### Description

1.  In backend, In prisma at user add new field i.e isAdmin: bool, In routes created admin folder in that i created controllers for adminLogin and fetching admin profile with adminAuth middleware, created routes for both and created zodSchema for admin.
2.  In frontend, created a login page and created a route for that and implement it on navbar.
3.  In admin folder, AdminLogin all the post is done and i browerrouter the AuthenticatedAdminRoute for accessing the dashboard.
4.  The design is reponse and admin activity is protected from outside world.
5.  For accessing the admin feature tha admin of the project should go in the mongodb database and make isAdmin user to true.
6.  All the proper toast message is used to show every error respectively.

### Related Issues
Fixes #320 

### Changes Made
New features: Created admin login backend and frontend.

### Screenshots

demo3

demo2

demo1

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Comment by MeetDOD** [comment]
@VaibhavArora314 All the things are sorted but the problem is when you login as admin you have to reload the page to update the navbar it is not updating in real time just like in user login and logout. please help or tell me the approach how to tackle it i am not much friendly with the prisma and all that's why 😢

**Comment by MeetDOD** [comment]
@VaibhavArora314 @Ultimateutkarsh11 can you show me the logs for deployment failed :)

**Comment by VaibhavArora314** [comment]
image

**Comment by MeetDOD** [comment]
@VaibhavArora314 It's already have all the packages in dependencies !

image

I think it's because of the folder structure ?

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 It's already have all the packages in dependencies !
> 
> image
> 
> I think it's because of the folder structure ?

let me check and find some solutions

**Comment by MeetDOD** [comment]
@VaibhavArora314 i think we should move admin folder to the frontend folder so it will use the frontend dependencies.

eg:

image

**Comment by MeetDOD** [comment]
@VaibhavArora314 I moved all the admin logic to frontend only because creating 2 react apps does not make any sense also all the logic is written in admin folder also created admiauth atom store for same and backend is same.

now, please tell me why deployement is failed ?

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 I moved all the admin logic to frontend only because creating 2 react apps does not make any sense also all the logic is written in admin folder also created admiauth atom store for same and backend is same.
> 
> now, please tell me why deployement is failed ?

please don't move the logic of admin to frontend, as I want to separate their logic based on their usage. also, the reason deployment fails is because the express server is trying to admin react app but you deleted the whole admin app, so it isn't able to find it.

**Comment by MeetDOD** [comment]
> > @VaibhavArora314 I moved all the admin logic to frontend only because creating 2 react apps does not make any sense also all the logic is written in admin folder also created admiauth atom store for same and backend is same.
> > now, please tell me why deployement is failed ?
> 
> please don't move the logic of admin to frontend, as I want to separate their logic based on their usage. also, the reason deployment fails is because the express server is trying to admin react app but you deleted the whole admin app, so it isn't able to find it.

oops, sorry i will do the changes as it was previously.
sorry for ininconvenience !

**Comment by MeetDOD** [comment]
@VaibhavArora314 now tell me the issues, i did exactly what you told me to do !

**Comment by MeetDOD** [comment]
@VaibhavArora314 I haven't worked on such project folder can you tell me in brief. how do i code in this folder and all or just update the readme file so that i could finish the work ASAP. 
It's a request from my side.
Thank you !

**Comment by VaibhavArora314** [comment]
I am thinking that you can split this task into two pull requests, one with backend logic and other with admin logic. Currently there are too many changes in this pull request and also I will be able to look into the reason as why there are dependency issues in the admin.

**Comment by MeetDOD** [comment]
> I am thinking that you can split this task into two pull requests, one with backend logic and other with admin logic. Currently there are too many changes in this pull request and also I will be able to look into the reason as why there are dependency issues in the admin.

@VaibhavArora314  i created issues for backend and frontend respectively you can close this one, i will start from new pr .

**Comment by VaibhavArora314** [comment]
closing this since this is being continued in other pull requests and issues

**Pull request closed without merging**
