### PR TITLE
Feat: Added social media links to user profile section successfully issue 226

### LINKED ISSUE #226: [Feature Request]: Add Social Media Links to User Profile Section
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We need to enhance the user profile section by adding social media links. This will allow users to display their social media profiles, making it easier for others to connect with them on various platforms.

### Use Case

A visitor wants to view another user's social media profiles to connect with them on various platforms.

### Benefits

A visitor wants to view another user's social media profiles to connect with them on various platforms.

### Add ScreenShots

_No response_

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [#226 ]

### Description

1.  In backend, I modified the user prisma schema and also updated the updateUserProfile controller as well as userProfileController and showUserProfileController to fetch the social links and their profiles.
2.  In frontend, I added the field for Twitter, facebook, github, linkedin and portfolio social links.
3.  Also modified the show user profile to see other profile section.
4.  Used icons which are responsive and also work in light/dark mode.

### Related Issues
Fixes #226 

### Changes Made
New feature:  Added social media links to user profile section.

### Screenshots

image

image

image

image

### Video

https://github.com/user-attachments/assets/fc84533b-8d82-4ca2-a9eb-4d57c69fa78e

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Review by akbatra567 — APPROVED** [review]

**Comment by MeetDOD** [comment]
@VaibhavArora314 can you please give level 3 because of frontend + backend integration and testing ! you review it 👍

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
You can remove the Facebook option as the edit user modal currently is too long vertically because of too many options.

**Comment by MeetDOD** [comment]
> You can remove the Facebook option as the edit user modal currently is too long vertically because of too many options.

Ok Noted 👍

**Comment by VaibhavArora314** [comment]
> > You can remove the Facebook option as the edit user modal currently is too long vertically because of too many options.
> 
> 
> 
> > You can remove the Facebook option as the edit user modal currently is too long vertically because of too many options.
> 
> @VaibhavArora314 that's why i created the issue #475 i will align nicely in all the devices. But if you want i will remove it , So i remove it or not the facebook icon ?

Don't remove it then

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
