### PR TITLE
Added contributors page

### PR DESCRIPTION
**Pull request by pani2004**
Solved issue #372 
- [ ] Unchecked box

- [ x] I have tested the changes locally
- [ x] Changes are backward-compatible

https://github.com/VaibhavArora314/StyleShare/assets/154724111/bdc73e38-35d4-416f-b2f9-fd74c2294355

### CODE REVIEW

**Comment by pani2004** [comment]
@VaibhavArora314 Pls review this PR!!!

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
looking good, just also make it theme responsive (dark and light theme)

**Comment by pani2004** [comment]
@VaibhavArora314 Made the changes

**Review by VaibhavArora314 — APPROVED** [review]

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by VaibhavArora314** [comment]
@akbatra567  kindly review this

**Comment by pani2004** [comment]
@akbatra567 Review this pls

**Pull request merged**
