### PR TITLE
feat: Community Interaction with comment section added successfully Issue 116

### LINKED ISSUE #116: [Feature Request]: Community Interaction with feedback sye
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Commenting system for users to give feedback on components of tailwindcss.
I will implement the comment section below every post in bottom.

I will Implement to comment section below the author at the end, like youtube and all.

image

### Use Case

Increasing user interaction.

### Benefits

By this feature the overall content in the webapp will increase.

### Add ScreenShots

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [#116]

### Description

1.  Created comment section in frontend as well as backend.
2.  Created Prisma schema, controllers, routes in backend.
3.  Created Comment file and added in Post file.
4.  API fetch and Posting comment is implemented.
5.  Responsive design.

### Related Issues
Fixes #116 

### Changes Made
New feature: Comment section .

### Screenshots
image

### Video

https://github.com/VaibhavArora314/StyleShare/assets/120380073/baa6cb47-22ce-48f2-819e-7394ba421ca4

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
looks good, just one thing user has to be verified to comment

**Comment by MeetDOD** [comment]
@VaibhavArora314 ok i will do it, where have you been all day ? busy day right :)

**Comment by MeetDOD** [comment]
@VaibhavArora314 see now, i had implemented it ONLY VERIFIED ONE CAN COMMENT !

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 ok i will do it, where have you been all day ? busy day right :)

I have my exams going on so will take some time to review sometimes

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
