### PR TITLE
Feat: Added responsiveness in posts page successfully issue 336

### LINKED ISSUE #336: [Bug]: The Posts page filters section is not responsive
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The fields are overlapping due to flex and grid problem in css.

### Expected behavior

Disruption of UI

### Add ScreenShots

image

### On which device are you experiencing this bug?

Mobile

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [#336 ]

### Description

1.  I used flex box and did justify between so that it divides it in two component like in one side filter, show trending button and on other side there is a search bar.
2.  The design is responsive in all devices respectively.

### Related Issues
Fixes #336 

### Changes Made
New features: Added responsiveness in posts page.

### Screenshots

image

image

image

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by akbatra567** [comment]
Seems to be good to me. In terms of responsiveness mentioned in the issue.

Note: It was not mentioned in the issue but seems a bit odd to me. @VaibhavArora314, Have a look. 

Screenshot 2024-07-01 at 10 19 52 PM

**Review by akbatra567 — APPROVED** [review]
LGTM

**Comment by MeetDOD** [comment]
@akbatra567 Sir, your are also the mentor for style share webapp?

**Comment by akbatra567** [comment]
> @akbatra567 Sir, your are also the mentor for style share webapp?

Yes, recently been assigned. Trying to be more active.

**Comment by MeetDOD** [comment]
> > @akbatra567 Sir, your are also the mentor for style share webapp?
> 
> Yes, recently been assigned. Trying to be more active.

Nice to meet you sir 😀

**Comment by VaibhavArora314** [comment]
> Seems to be good to me. In terms of responsiveness mentioned in the issue.
> 
> Note: It was not mentioned in the issue but seems a bit odd to me. @VaibhavArora314, Have a look. 
> 
> Screenshot 2024-07-01 at 10 19 52 PM
> 

Yes we can create a separate issue for the navbar as the theme mode button looks odd on small devices

**Comment by MeetDOD** [comment]
@VaibhavArora314 I am working in admin folder but whenever i call api its give 404 error, i did npm run build but it still give that error only, did i have to configure something or any other command i have to run ?

Please help me !

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by MeetDOD** [comment]
@akbatra567 please add gssoc level

**Comment by MeetDOD** [comment]
@VaibhavArora314 

> @akbatra567 please add gssoc level

**Comment by MeetDOD** [comment]
> > @VaibhavArora314 I am working in admin folder but whenever i call api its give 404 error, i did npm run build but it still give that error only, did i have to configure something or any other command i have to run ?
> > Please help me !
> 
> This should not be the case, have you uncommented the lines in app.tsx?

Ya I am running the app same as i am doing in frontend app.tsx, but still not working :(

**Comment by MeetDOD** [comment]
I am stuck in this

**Comment by VaibhavArora314** [comment]
> > > @VaibhavArora314 I am working in admin folder but whenever i call api its give 404 error, i did npm run build but it still give that error only, did i have to configure something or any other command i have to run ?
> > > Please help me !
> > 
> > 
> > This should not be the case, have you uncommented the lines in app.tsx?
> 
> Ya I am running the app same as i am doing in frontend app.tsx, but still not working :(

it may be due to the case of no such admin user exists where the status code returned was 404, I have updated the status code. also, make sure you are logging in with an account that has the isAdmin property set to true.

**Pull request merged**
