### PR TITLE
feat: Added Showing webapp features with card in style share successfully issue 214

### LINKED ISSUE #214: [Feature Request]: Showing webapp features with card
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

1. Every website have their feature section where they showcase their website ability to delivered to the users.
2. For example in style share there can be option like robust, beautifull, responsive designs etc etc...
3. In this way we can implement the features section.

### Use Case

User awareness.

### Benefits

User Information.

### Add ScreenShots

Eg: Learning webapp

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [#214 ]

### Description

1. I created 4 feature cards which show different feature in style share.
2. The features include: Responsive Design, Leaderboard, Personalization, Customizable Code Snippets.
3. The design is completely responsive in any devices.
4. Implemented with the feature with creating feature.tsx and added it in Home.tsx.

### Related Issues
Fixes #214 

### Changes Made
New features: Added Showing webapp features with card in style share.

### Screenshots

image

image

image

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Comment by MeetDOD** [comment]
@VaibhavArora314 the cursor is not matching the theme of the wbsite because of the pink color

**Comment by manikumarreddyu** [comment]
> @VaibhavArora314 the cursor is not matching the theme of the wbsite because of the pink color

i am also thinking the same..we need to change it

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
looks good just move it below about section

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 the cursor is not matching the theme of the wbsite because of the pink color

I was thinking the same, you can raise an issue for the same

**Comment by MeetDOD** [comment]
> looks good just move it below about section

@VaibhavArora314  i think the user will first see the feature and then the about.

eg: 

image

image

but i can change it as per your request 😄

**Comment by VaibhavArora314** [comment]
> > looks good just move it below about section
> 
> @VaibhavArora314 i think the user will first see the feature and then the about.
> 
> eg:
> 
> image
> 
> image
> 
> but i can change it as per your request 😄

ok, just resolve the conflicts

**Comment by MeetDOD** [comment]
@VaibhavArora314 Done 👍

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
