### PR TITLE
Feat: Updated update profile form UI and removed facebook link from frontend successfully Issue 475

### LINKED ISSUE #475: [Feature Request]: Styling the update profile form
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently the form is not looking nice instead i will use the same pop up as used in the admin panel to read the contact us email sent by the users.

### Use Case

UI/UX

### Benefits

Profile section enhancement

### Add ScreenShots

Current:

image

Approach:

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [#475 ]

### Description

1. In backend, I removed the facebook link from prisma, controller and routes because facebook is not that important also the form is taking big space and will not look nice in mobile.
2. In frontend, with the help of model I achieved the beautiful form/model for update profile by the user.

### Related Issues
Fixes #475 

### Changes Made
New feature: Updated update profile form UI and removed facebook link from frontend.

### Screenshots

image

image

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by VaibhavArora314** [comment]
I am keeping this level 1 @MeetDOD, as Facebook link removal was not part of this issue and was part of your previous pull request.

**Comment by MeetDOD** [comment]
> I am keeping this level 1 @MeetDOD, as Facebook link removal was not part of this issue and was part of your previous pull request.

So, if I put back the facebook link then it will be level 2 🤔

**Comment by MeetDOD** [comment]
@VaibhavArora314 just see the styling efforts done with the Model I hope you understand rest I will leave it to you I will not say anything about it 🙏

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by VaibhavArora314** [comment]
> > I am keeping this level 1 @MeetDOD, as Facebook link removal was not part of this issue and was part of your previous pull request.
> 
> So, if I put back the facebook link then it will be level 2 🤔

Nah, this issue was supposed to be level1 and Facebook link removal was not part of this that's why i said that I am marking this as level 1

**Review by akbatra567 — APPROVED** [review]

**Comment by MeetDOD** [comment]
> > > I am keeping this level 1 @MeetDOD, as Facebook link removal was not part of this issue and was part of your previous pull request.
> > 
> > 
> > So, if I put back the facebook link then it will be level 2 🤔
> 
> Nah, this issue was supposed to be level1 and Facebook link removal was not part of this that's why i said that I am marking this as level 1

Ok let's leave the facebook social link part aside beside that I created a Model and applied style to it, you can consider that and give level 2  if possible 👍

**Pull request merged**
