### PR TITLE
updated login and signup

### PR DESCRIPTION
**Pull request by Sailesh3000**
# Pull Request

### Title
Updated login and signup form for this issue #395 
### Checklist 
- [X ] I have tested the changes locally
### Screenshots (if applicable)
image

Please assign this PR gssoc and level label thank you.

### CODE REVIEW

**Comment by Sailesh3000** [comment]
Why my deployment is failing can you please check it.

**Comment by VaibhavArora314** [comment]
image
@Sailesh3000 resolve error

**Review by Ultimateutkarsh11 — CHANGES_REQUESTED** [review]
@Sailesh3000 also resolve the merge conflicts

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
Some changes
1. In current website signup page:
image
After your changes:
image
Make it look like before because it is not looking good
2. The page route should also update when the user changes signin and signup page
3. Is it possible to improve the styling of this bar as it is not looking very good
image

**Comment by Sailesh3000** [comment]
image
image
Now i think its good page route is also changing

**Review by VaibhavArora314 — COMMENTED** [review]
image
1. In dark mode, the option other than selected is too light
2. also if I am on the signin page, and I press the signup button of this bar the route is not updated even though signup page is shown

**Comment by Sailesh3000** [comment]
Sorry I did not notice that. I think its ok now.

**Comment by Sailesh3000** [comment]
I think it's ok now Please still you need any changes please inform.

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by VaibhavArora314** [comment]
resolve merge conflicts rest is good

**Comment by Sailesh3000** [comment]
yeah done with that

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Review by akbatra567 — APPROVED** [review]

**Pull request merged**
