### PR TITLE
Designed the Contributors Page Match to Website Theme and Made it Responsive

### LINKED ISSUE #540: Design the Contributors Page Match to Website Theme and Make it Responsive
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @VaibhavArora314 

We need to design and implement a Contributors Page for our project, ensuring it matches the existing website theme and is fully responsive.

image

image

### Use Case

N/A

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by RadhikaMalpani1702**
### Description
Hey @VaibhavArora314 

- issue closes #540 

I have Designed the Contributors Page Match to Website Theme and Made it Responsive

image

image

image

image

### Checklist 

- [X] I have tested the changes locally
- [X] Documentation has been updated (if necessary)
- [X] Changes are backward-compatible

### CODE REVIEW

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
Looks great, just add a little margin on the sides or reduce the size of the card for smaller devices since in smaller devices it doesn't look good.
image

**Comment by VaibhavArora314** [comment]
@RadhikaMalpani1702 any updates?

**Comment by RadhikaMalpani1702** [comment]
@VaibhavArora314 Yes I'm doing, when I fix the card in mobile view it  changes card no. to 4 in each row in desktop view

**Comment by RadhikaMalpani1702** [comment]
@VaibhavArora314  I have made the changes please take a look

image

image

**Review by VaibhavArora314 — APPROVED** [review]

**Review by akbatra567 — APPROVED** [review]

**Pull request merged**
