### PR TITLE
ADDED trending posts successfully

### PR DESCRIPTION
**Pull request by manikumarreddyu**
# Pull Request

### Title

ADDED Trending posts 

### Description

It gives top 6 posts based on user reaction count

### Related Issues

Fixes: #248 

### Changes Made

added new compnent 
1. TrendingPosts.tsx

2.getTrendingPostsController  (in post/controller.ts)

some other small changes

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)

It is better to see in preview

### Additional Notes

nothing
Footer

### CODE REVIEW

**Comment by manikumarreddyu** [comment]
hey @VaibhavArora314 check it once, suggest me any changes.

as of now it showing trending posts based on reactions count.
In further issues we will make more changes.
if we want to do all at once ..the conflicts will increase.

Thank you.!

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
resolve merge conflicts

**Comment by manikumarreddyu** [comment]
Hey @VaibhavArora314 check once

**Comment by manikumarreddyu** [comment]
hey @VaibhavArora314 check it once

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
image

the filter menu should come below filter option, you can move the filter button to the left

**Comment by manikumarreddyu** [comment]
Okay @VaibhavArora314

**Comment by manikumarreddyu** [comment]
HEY @VaibhavArora314  please merge this PR before other PR's orelse i will get more merge conflicts than others..
please consider my request 
Thank you

**Comment by manikumarreddyu** [comment]
hey @VaibhavArora314 please check it once

**Comment by manikumarreddyu** [comment]
hey @VaibhavArora314  @Ultimateutkarsh11 please check it once

**Review by VaibhavArora314 — APPROVED** [review]

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by manikumarreddyu** [comment]
hey @Ultimateutkarsh11 it is given as level 3 by  @VaibhavArora314 previously.. i closed that PR due to huge merge conflicts..
check it once #275 here

**Pull request merged**
