### PR TITLE
Adding new sections in home page

### PR DESCRIPTION
**Pull request by manikumarreddyu**
# Pull Request

### Title

Adding new sections in home page
1.FAQ
2.CODE EDITOR SHOWCASE

### Description

Adding new sections in home page

### Related Issues

Fixes: #211 
### Changes Made

1. added faq.tsx
2. added showcase.tsx
3. global css file -- animations added
4. home.tsx -- added faq,showcase

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)

showcase
image
faq
image

### CODE REVIEW

**Comment by manikumarreddyu** [comment]
hey @VaibhavArora314 check it once , and let me know any changes required.
Thank you!!

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
Except for the built-in terminal line everything looks good. You can remove that point.

**Comment by manikumarreddyu** [comment]
sure @VaibhavArora314

**Comment by manikumarreddyu** [comment]
hey @VaibhavArora314 check it once , and let me know any changes required.
Thank you!!

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
