### PR TITLE
feat: Implemented reCAPTCHA v3

### LINKED ISSUE #65: Feat: reCAPTCHA Implementation
Implementing reCAPTCHA v3 on the website will help in enhancing security, preventing spam and unauthorized access, protecting user data.
This also helps in preventing automated bots from accessing or submitting forms on the website.

Screenshot: 

Screenshot 2024-05-18 113014

### PR DESCRIPTION
**Pull request by antriksh-9**
# Pull Request

### Title
Implemented reCAPTCHA v3

### Description
Integrated reCAPTCHA v3 in signin form.

### Related Issues

Closes #65 

### Changes Made

- Added recaptcha widget
- Integrated recaptcha on signin form.
- Configured site and secret key
- Implemented recaptcha verification process

### Checklist 

- [x] I have tested the changes locally
- [ ] Documentation has been updated (if necessary)
- [ ] Changes are backward-compatible

### Screenshots (if applicable)

Screenshot 2024-06-08 134102

### CODE REVIEW

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
Look into this.
image
image

and also implement this for user signup also

**Comment by antriksh-9** [comment]
> Look into this. image image
> 
> and also implement this for user signup also

What is the full error message?

**Comment by VaibhavArora314** [comment]
Closing due to inactivity

**Comment by antriksh-9** [comment]
Hey @VaibhavArora314 I am working on this, it's just I am not able to configure what's the exact problem, as the widget is properly appearing in localhost.

**Comment by antriksh-9** [comment]
Will solve the issue in few days.

**Pull request closed without merging**
