### PR TITLE
Added Google Translator

### LINKED ISSUE #378: [Feature Request]: Add Google Translator Integration
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to request the addition of Google Translator integration into the project. This feature would significantly enhance the user experience by providing seamless translation capabilities.

### Use Case

Accessibility: Non-native speakers would find it easier to use the application.
Global Reach: Expanding the usability of the application to a global audience.
User Convenience: Simplifies the process for users needing translation services within the app.

### Benefits

_No response_

### Add ScreenShots

lang

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by AsmitaMishra24**
### Description
Added google translator and also removed language translation implemented using react18next.

### Related Issues
Fixes #378 

### Changes Made
1. Removed language translation.
2. Added Google translator.

### Checklist 
- [X] I have tested the changes locally
- [ ] Documentation has been updated (if necessary)
- [X] Changes are backward-compatible

### Screenshots (if applicable)
https://github.com/user-attachments/assets/de2ab589-6ff3-4940-aa8e-a1dfbcae73d8

### CODE REVIEW

**Comment by AsmitaMishra24** [comment]
@VaibhavArora314, Please review the PR. If any changes are needed, let me know and I will make them.

**Comment by VaibhavArora314** [comment]
image
resolve these errors

**Comment by AsmitaMishra24** [comment]
> image resolve these errors

@VaibhavArora314, done

**Review by akbatra567 — APPROVED** [review]
Looks good to me for the files changed. Not sure if we have any other files which mentions google translate.

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
