### PR TITLE
Feat: Added/fetched user avatar in admin panel successfully issue 548

### LINKED ISSUE #548: [Feature Request]: Showing user avatar in all tables in admin panel
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Sinec with the api also the user avatar is not appearing so i will fix this and fetch it in the admin panel

### Use Case

Admin engagement

### Benefits

Admin benefit

### Add ScreenShots

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [ #548 ]

### Description

1. In backend, for every controller I have added avatar:true to fetch in the admin panel.
2. In assests, I added the image to get /admin/... and replace it with the /app/...
3. In admin, I am fetching the avatar url from api created.
4. The design is responsive.

### Related Issues
Fixes #548 

### Changes Made
New feature: Added/fetched user avatar in admin panel.

### Screenshots

image

image

image

image

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
instead of replacing the whole string why don't we just replace admin with app?

**Comment by MeetDOD** [comment]
@VaibhavArora314 I think this will make negligible  difference, but never mind I did the changes as you told me 👍

**Comment by MeetDOD** [comment]
@VaibhavArora314 please give level 2 if possible 👍

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 please give level 2 if possible 👍 

I think there was not too much work in this one and it should be under level 1.

**Comment by MeetDOD** [comment]
> > @VaibhavArora314 please give level 2 if possible 👍
> 
> I think there was not too much work in this one and it should be under level 1.

😭 bro they just change margin bottom and get level 1, then what is the difference between them and me ?

**Comment by VaibhavArora314** [comment]
> > > @VaibhavArora314 please give level 2 if possible 👍
> > 
> > I think there was not too much work in this one and it should be under level 1.
> 
> 😭 bro they just change margin bottom and get level 1, then what is the difference between them and me ?

You got a point

**Review by akbatra567 — APPROVED** [review]

**Pull request merged**
