### PR TITLE
Added light/dark mode 

### PR DESCRIPTION
**Pull request by manikumarreddyu**
# Pull Request

### Title

Added light/dark mode 

### Description

Added light/dark mode 

### Related Issues

fixes : #115 

### Changes Made

many changes

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)

can see in preview

### Additional Notes

nothing

Footer

### CODE REVIEW

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
1. NewPost Page
image
2. Filter button and search input color
image
3. Provide only 1 button for theme, remove button for theme for code window
image
4. Loader coming in dark mode even when light mode selected
image

**Comment by VaibhavArora314** [comment]
I suggest that you break the pr into smaller prs, since there will be various conflicts and it will be easier for you to resolve and easier for me to review

**Comment by manikumarreddyu** [comment]
> I suggest that you break the pr into smaller prs, since there will be various conflicts and it will be easier for you to resolve and easier for me to review

okay @VaibhavArora314

**Comment by manikumarreddyu** [comment]
please merge upto these .
i will add remaining in new prs

**Comment by manikumarreddyu** [comment]
one by one i will add in new prs , if you merge this

**Comment by manikumarreddyu** [comment]
upto now
 
faq.tsx
features.tsx
navbar.tsx
postcard.tsx
showcase.tsx
about.tsx
comment,tsx
contactus.tsx
editpost.tsx
favourites.tsx
home.tsx
homepage.tsx
homepageposts.tsx
leaderboard.tsx
policy.tsx
posts.tsx
profile.tsx
showprofile.tsx
sigin.tsx
signup.tsx 

are completed

**Comment by manikumarreddyu** [comment]
creating new pr for remaining prs

**Comment by manikumarreddyu** [comment]
merge these without any hesitation...

**Comment by manikumarreddyu** [comment]
hey @VaibhavArora314 completed all
you can merge it

**Comment by manikumarreddyu** [comment]
PLEASE MERGE UPTO THIS ..Everything is completed.

IF there is any suggestions for that we create it under new issue...otherwise all the hard work will go off...we will stuck in a loop

**Comment by manikumarreddyu** [comment]
PLEASE MERGE UPTO THIS ..Everything is completed.

IF there is any suggestions for that we create it under new issue...otherwise all the hard work will go off...we will stuck in a loop

**Review by VaibhavArora314 — APPROVED** [review]
overall this is looking good. there are minor bugs that can be solved in separate issues.

**Pull request merged**
