### PR TITLE
Google and other login feature are implimented

### LINKED ISSUE #46: Implement Google Signup Functionality
Users should be able to sign up using their Google tokens for authentication.

This feature enhances user convenience by allowing them to sign up using their Google accounts, reducing the need to remember additional login credentials.

Screenshots
Actual:
image

Expected :
image

Could you please Assign this issue to me under gssoc

### LINKED ISSUE #52: Google Sign Up Feature Implementation and Re-Designing the Sign up and Login Form
Describe the bug
Hello @VaibhavArora314 as we can see If we visit the home page of the website and go to the Sign form then we can see that there is no functionality for signing in with another platform such as Google, LinkedIn, Facebook and Github, etc.

To Reproduce

- Open the home page at https://style-share.vercel.app/app
- Open the Sign in and Sign up form 
- Observe the design and absence of Sign with Google and another platform in the Signup form.
- I want to Introduce this feature

Expected behavior
Implementing Sign up functionality by Google and many other platforms and improving the design of sign-up and Login 
image

Screenshots
Before the problem is that there is no feature of Sign in or Login with Google.
image

Hey PA,
I want to work on this issue once you assign me under GSSoC'24 and please assign level 3 to this issue 🙏. Thank You!

### LINKED ISSUE #63: Improve UI of  Sign In page
The UI of sign in page is not very appealing . i would like yo re-design it.
Screenshot 2024-06-01 143346

I will correct the alignment of buttons and add a heading and try to improve the overall UI as well as UX

Kindly assign me this issue.
Best regards

### LINKED ISSUE #64: Improvement of sign up page
Screenshot 2024-06-01 143619
The headings are very light in color and these is no title in the card.
I will also add a parallax effect to enhance the user interaction

### PR DESCRIPTION
**Pull request by ManishBirthlia**
# Pull Request

### Title
Google Sign-Up Feature Implementation and Re-Designing the Sign-Up and Login Form

### Description
I tried out this new library called @kinde-oss/kinde-auth-react. I didn't replace your authentication code, just commented it out and added my code. I didn't delete or modify any existing code, just added new login and sign-in buttons.

### Related Issues
Fixes #52 
Fixes #64 
Fixes #63 
Fixes #46   

### Changes Made
- [x] I Have Commneted your previous Sign In and Sign up code in "Navbar.jsx" onced opened you will able to understand
- [x] Mostly changes I have done in "Navbar.jsx" and then I changed "isLoggedIn" to "isAuthenticated" which is an in-build
- [x] I have just used this new library "@kinde-oss/kinde-auth-react" 

### Checklist 
- [x] Google Login
- [x] Facebook Login
- [x] Twitter Login
- [x] Github Login
- [x] Microsoft Login
- [x] Apple Login
- [x] Linkedin Login
- [x] Discord Login
- [x] I have tested the changes locally
- [x] Changes are backward-compatible
- [x] Everything working Properly

### Screenshots (if applicable)

https://github.com/VaibhavArora314/StyleShare/assets/96776615/7b605a18-46ba-4d67-81cd-df90ea4de96f

### Additional Notes
@VaibhavArora314 you have to make an account on Kinde and provide your Client ID and Domain and then you will be able to see all these changes 😉

### CODE REVIEW

**Comment by ManishBirthlia** [comment]
@VaibhavArora314 This is the Preview website you can go to see and tell me what you think about it
https://style-share-git-fork-manishbi-1bad6d-vaibhavs-projects-0c395dc9.vercel.app/app/

**Comment by VaibhavArora314** [comment]
hey so first of all don't work on any issue unless it's assigned to you as there can be others assigned the same issue already and it can cause your work to be wasted.

secondly, the auth logic implemented redirects the user to the Kinde website where authentication is handled but we wanted it to be integrated within our own website

**Comment by ManishBirthlia** [comment]
> hey so first of all don't work on any issue unless it's assigned to you as there can be others assigned the same issue already and it can cause your work to be wasted.
> 
> secondly, the auth logic implemented redirects the user to the Kinde website where authentication is handled but we wanted it to be integrated within our own website

Yes exactly that's why i asked you if you want this or not then you reply with that you are open to new things but np🙌 i also learned a lot from your project so no worries and i will keep in mind to worked only if i am assigned to it 😂

**Comment by VaibhavArora314** [comment]
> > hey so first of all don't work on any issue unless it's assigned to you as there can be others assigned the same issue already and it can cause your work to be wasted.
> > secondly, the auth logic implemented redirects the user to the Kinde website where authentication is handled but we wanted it to be integrated within our own website
> 
> Yes exactly that's why i asked you if you want this or not then you reply with that you are open to new things but np🙌 i also learned a lot from your project so no worries and i will keep in mind to worked only if i am assigned to it 😂

sorry for any confusion, but when I checked out their website I did not know they will use their website as the mediator 😅

**Comment by ManishBirthlia** [comment]
Yea and np yaar besides understanding your project which i always love to do 😉 implementing login features using Kinde is hardly any problem

**Comment by ManishBirthlia** [comment]
> sorry for any confusion, but when I checked out their website I did not know they will use their website as the mediator 😅

Yea and np yaar besides understanding your project which i always love to do 😉 implementing login features using Kinde is hardly any problem

**Comment by VaibhavArora314** [comment]
> > sorry for any confusion, but when I checked out their website I did not know they will use their website as the mediator 😅
> 
> Yea and np yaar besides understanding your project which i always love to do 😉 implementing login features using Kinde is hardly any problem

feel free to raise any issues, I will be happy to assign them to you. also, there are some issues I raised which are not assigned to anyone yet

**Comment by ManishBirthlia** [comment]
@VaibhavArora314 i would have happily taken these issues but i have to build a complete project using Shephard liberary because i joined a Quest in SSOC'24 and there is prize money for completing the Quest 😅😂..... So i will come back to raise more issues on your project 🙌👍

**Pull request closed without merging**
