### PR TITLE
testimonials

### PR DESCRIPTION
**Pull request by manikumarreddyu**
# Pull Request

### Title
added Testimonials

### Description
added Testimonials

### Related Issues
Fixes : #192 

### Changes Made
added new file in components folder
TestimonialSlider.tsx

made some changes in home.tsx

### Checklist 
- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)
image
image

### CODE REVIEW

**Comment by manikumarreddyu** [comment]
hello @VaibhavArora314 check it once..

**Comment by manikumarreddyu** [comment]
image
 hey @VaibhavArora314  changed to dummy

**Comment by manikumarreddyu** [comment]
i have made a perfect navbar in another branch of mine
if you are okay with it i will raise a PR
Please consider my request @VaibhavArora314 

### Screenshots (if applicable)

navbar Before
image


navbar After

image

footer before
image

footer after
image

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by VaibhavArora314** [comment]
> i have made a perfect navbar in another branch of mine if you are okay with it i will raise a PR Please consider my request @VaibhavArora314
> 
> ### Screenshots (if applicable)
> navbar Before image
> 
> navbar After
> 
> image
> footer before image
> 
> footer after image

raise a PR for adding a logo in the footer and use the logo which is currently being used not the one which you created. As for the navbar, it has been implemented.

**Pull request merged**
