### PR TITLE
feat: Implemented Leaderboard approach in style share successfully issue 132

### LINKED ISSUE #132: [Feature Request]: Leaderboard approach in style share
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I am thinking of the new features and this come in my mind, how about the leaderboard for the contributors who gives tailwind css componenets.

I will give top 3 user 1st,2nd,3rd title on the basis of the number of components they uploaded on the webapp.

The leaderboard will be visual appealing. so, its engage the user in competition result in more users to the webapp.

### Use Case

Engaging users. 

### Benefits

Ranks will be given example as 1st => Gold, 2nd => silver, 3rd => bronze and rest are given simple badges.

### Add ScreenShots

**Example:**

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [#132}

### Description

1.  Created controller for leaderboard while filter the users with there likes
2.  Created routes for implementing in frontend.
3.  In frontend created new file and new route in the navbar.
4.  Fetch in all user details table also giving first 3 ranks as trophy and rest in ranks

### Related Issues
Fixes #132 

### Changes Made
New features: Leaderboard approach in style share

### Screenshots

1.  LeaderBoard UI.

image

2.  Additional feature Added user profile image in comment section which enhance the overall UI.

image

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Comment by MeetDOD** [comment]
@VaibhavArora314 I think this feature deserve **LEVEL 3** label. I am not forcing, you can evaluate by yourself if this deserve's or not. Thank You 😊

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
Limit the leaderboard to only top 10 users and if the current user is present in the list,  his/her name should be highlighted.

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 I think this feature deserve **LEVEL 3** label. I am not forcing, you can evaluate by yourself if this deserve's or not. Thank You 😊

the labels on the issue are initial assessments and based on work I update the labels so don't worry.

**Comment by MeetDOD** [comment]
> Limit the leaderboard to only top 10 users and if the current user is present in the list, his/her name should be highlighted.

Okay i will do that

**Comment by MeetDOD** [comment]
@VaibhavArora314  I implemented both the changes as requested.

example:

image

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
instead of username compare using user id while highlighting current user 

image

**Comment by MeetDOD** [comment]
> instead of username compare using user id while highlighting current user
> 
> image

Nice catch 😀 , I will fix this give me a minute !

**Comment by MeetDOD** [comment]
@VaibhavArora314 Done check now,

image

**Comment by VaibhavArora314** [comment]
Just one last thing, we can make the leaderboard publicly accessible, it doesn't need to be an authenticated route

**Comment by MeetDOD** [comment]
I see

**Comment by MeetDOD** [comment]
See Now 🙏

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by MeetDOD** [comment]
@VaibhavArora314 It was level 2 or level 3 ?

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 It was level 2 or level 3 ?

Oh sorry forgot to add labels

**Comment by MeetDOD** [comment]
Bruh 😭

**Pull request merged**
