### PR TITLE
Enhance Navbar

### PR DESCRIPTION
**Pull request by naisargi17**
# Pull Request

### Title
background of navbar

### Description
changed the navbar .

### Checklist 

- [X ] I have tested the changes locally
- [ X] Documentation has been updated (if necessary)
- [X] Changes are backward-compatible

### Screenshots (if applicable)
(https://github.com/VaibhavArora314/StyleShare/assets/111778403/a90533a2-cfad-4dc4-8d14-136cb595f3d3)

Footer

### CODE REVIEW

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by manikumarreddyu** [comment]
hey @VaibhavArora314   @naisargi17  after this PR is merged code editor is no more coming ..kindly please check it once

**Comment by manikumarreddyu** [comment]
dont worry @naisargi17 we are working on it.it will be resolved soon..moreover your design is excellent.

**Comment by naisargi17** [comment]
I apologize for my inconvenience . Thank you for your  Understanding & appreciation.

**Comment by manikumarreddyu** [comment]
image

can you please review my pull request
i am not getting well PR #219

**Comment by naisargi17** [comment]
<li className="mt-2">
                  <Link to="/app/code" className={getNavLinkClass("/app/code")} onClick={closeMenu}>
                    {t("code")}
                  </Link>
                </li>  
this one was correct @manikumarreddyu

**Comment by naisargi17** [comment]
[[<li className="mt-2">
                  <Link to="/app/code" className={getNavLinkClass("/app/code")} onClick={closeMenu}>
                    {t("code")}
                  </Link>
                </li> ]]]
was correct @manikumarreddyu

**Comment by manikumarreddyu** [comment]
okay...if there any errors i will update you

**Comment by naisargi17** [comment]
image
this was correct @manikumarreddyu

**Comment by manikumarreddyu** [comment]
yeah..finally we did it.. @naisargi17 

image

**Comment by manikumarreddyu** [comment]
i cant able to see names in navbar like Home , New ,Favourites...where are they in the code

**Comment by naisargi17** [comment]
Big Thanks to you .  see scroll up u will see it 
image

**Comment by manikumarreddyu** [comment]
import { useState } from "react";
import { useRecoilValue, useSetRecoilState } from "recoil";
import { loggedInState, tokenState } from "../store/atoms/auth";
import { Link, useLocation } from "react-router-dom";
import toast from "react-hot-toast";

const Navbar = () => {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const setTokenState = useSetRecoilState(tokenState);
  const isLoggedIn = useRecoilValue(loggedInState);
  const location = useLocation();

  const toggleMenu = () => {
    setIsMenuOpen(!isMenuOpen);
  };

  const closeMenu = () => {
    setIsMenuOpen(false);
  };

  const handleLogout = () => {
    localStorage.removeItem("token");
    setTokenState("");
    closeMenu();
    toast.success('Logged out successfully')
  };

  const getNavLinkClass = (path: string) => {
    return location.pathname === path
      ? "block py-2 px-3 bg-blue-700 rounded md:bg-transparent md:p-0 text-white md:text-blue-500"
      : "block py-2 px-3 rounded md:border-0 md:p-0 text-white md:hover:text-blue-500 hover:bg-gray-700 hover:text-white md:hover:bg-transparent";
  };

  return (
    <nav className="border-gray-200 bg-gray-800 fixed top-0 left-0 w-full z-10 py-1 bg-gradient-to-r from-pink-900 to-gray-800">
      <div className="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <Link to="/app" className="flex items-center space-x-3 rtl:space-x-reverse" onClick={closeMenu}>
          <span className="self-center text-3xl leading-6 font-semibold whitespace-nowrap text-white font-teko">
            Style Share
          </span>
        </Link>
       <button
          onClick={toggleMenu}
          type="button"
          className="inline-flex items-center p-2 w-10 h-10 justify-center text-sm rounded-lg md:hidden focus:outline-none focus:ring-2 text-gray-400 hover:bg-gray-700 focus:ring-gray-600"
          aria-controls="navbar-default"
          aria-expanded={isMenuOpen ? "true" : "false"}
        >
          <span className="sr-only">Open main menu</span>
          <svg
            className="w-5 h-5"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 17 14"
          >
            <path
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              d="M1 1h15M1 7h15M1 13h15"
            />
          </svg>
        </button>
        <div
          className={`${
            isMenuOpen ? "block" : "hidden"
          } w-full md:block md:w-auto transition-all duration-300 ease-in-out`}
          id="navbar-default"
        >
          <ul className="font-medium flex flex-col p-4 md:p-0 mt-4 border rounded-lg md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0">
            <li className="mt-2 md:mb-0">
              <Link to="/app" className={getNavLinkClass("/app")} aria-current="page" onClick={closeMenu}>
                Home
              </Link>
            </li>
            <li className="mt-2">
              <Link to="/app/posts" className={getNavLinkClass("/app/posts")} onClick={closeMenu}>
                Posts
              </Link>
            </li>
            <li className="mt-2">
                  <Link to="/app/leaderboard" className={getNavLinkClass("/app/leaderboard")} onClick={closeMenu}>
                    Leaderboard
                  </Link>
                </li>
            {!isLoggedIn ? (
              <div className="flex flex-col md:flex-row md:space-x-4">
                <li className="mb-2 md:mb-0">
                  <Link
                    to="/app/signin"
                    className="block py-2 px-3 rounded-full text-white bg-gradient-to-l from-blue-400 to-pink-500 duration-300 transition-colors hover:from-pink-500 hover:to-blue-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-pink-500 "
                    onClick={closeMenu}
                  >
                    Sign in
                  </Link>
                </li>
                <li>
                  <Link
                    to="/app/signup"
                    className="block py-2 px-3 rounded-full text-white bg-gradient-to-l from-blue-400 to-pink-500 duration-300 transition-colors hover:from-pink-500 hover:to-blue-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-pink-500"
                    onClick={closeMenu}
                  >
                    Sign up
                  </Link>
                </li>
              </div>
            ) : (
              <>
                <li className="mt-2">
                  <Link to="/app/new-post" className={getNavLinkClass("/app/new-post")} onClick={closeMenu}>
                    New Post
                  </Link>
                </li>
                <li className="mt-2">
                  <Link to="/app/profile" className={getNavLinkClass("/app/profile")} onClick={closeMenu}>
                    Profile
                  </Link>
                </li>
                <li className="mt-2">
                  <Link to="/app/fav" className={getNavLinkClass("/app/fav")} onClick={closeMenu}>
                    Favorite
                  </Link>
                </li>
                <li className="mt-2">
                  <button
                    className="block py-2 px-3 rounded md:border-0 md:p-0 text-white md:hover:text-blue-500 hover:bg-gray-700 hover:text-white md:hover:bg-transparent w-full text-left"
                    onClick={handleLogout}
                  >
                    Logout
                  </button>
                </li>
              </>
            )}
          </ul>
        </div>
      </div>
    </nav>
  );
};

export default Navbar;

**Comment by manikumarreddyu** [comment]
in the before code everything is so simple...no hidings

but the code which you have written i have not able to find pages names in the code..still i am not getting
but somehow i managed to rectify the error

**Comment by manikumarreddyu** [comment]
> Big Thanks to you . see scroll up u will see it image

 i am not getting you @naisargi17

**Comment by manikumarreddyu** [comment]
can you please give your linkindin profile @naisargi17 
i need some clarity regarding the code

**Comment by naisargi17** [comment]
import { useState } from "react";
import { useRecoilValue, useSetRecoilState } from "recoil";
import { loggedInState, tokenState } from "../store/atoms/auth";
import { Link, useLocation } from "react-router-dom";
import toast from "react-hot-toast";
import logo from "../assets/favicon.png";
import { useTranslation } from "react-i18next";

const Navbar = () => {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const setTokenState = useSetRecoilState(tokenState);
  const isLoggedIn = useRecoilValue(loggedInState);
  const location = useLocation();
  const { t } = useTranslation();

  const toggleMenu = () => {
    setIsMenuOpen(!isMenuOpen);
  };

  const closeMenu = () => {
    setIsMenuOpen(false);
  };

  const handleLogout = () => {
    localStorage.removeItem("token");
    setTokenState("");
    closeMenu();
    toast.success("Logged out successfully");
  };

  const getNavLinkClass = (path: string) => {
    return location.pathname === path
      ? "block py-2 px-3 bg-blue-600 rounded md:bg-transparent md:p-0 text-white md:text-blue-300"
      : "block py-2 px-3 rounded md:border-0 md:p-0 text-white md:hover:text-blue-300 hover:bg-blue-400 hover:text-white md:hover:bg-transparent";
  };

  return (
    <nav className="bg-gradient-to-r from-[#6a11cb] via-[#ab67df] to-[#2575fc]  fixed w-full z-20 top-0 start-0 ">
      <div className="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <Link
          to="/app"
          className="flex items-center space-x-3 rtl:space-x-reverse"
          onClick={closeMenu}
        >
          Styleshare Logo
          <span className="self-center justify-between text-2xl font-bold whitespace-nowrap text-white font-mono">
            {t("navbar.logo")}
          </span>
        </Link>
        <button
          onClick={toggleMenu}
          type="button"
          className="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-100 rounded-lg md:hidden hover:bg-blue-400 focus:outline-none focus:ring-2 focus:ring-gray-200"
          aria-controls="navbar-default"
          aria-expanded={isMenuOpen ? "true" : "false"}
        >
          <span className="sr-only">Open Menu</span>
          <svg
            className="w-5 h-5"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 17 14"
          >
            <path
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              d="M1 1h15M1 7h15M1 13h15"
            />
          </svg>
        </button>
        <div
          className={`${
            isMenuOpen ? "block" : "hidden"
          } w-full md:block md:w-auto transition-all duration-300 ease-in-out`}
          id="navbar-default"
        >
          <ul className="font-medium flex flex-col p-4 text-lg md:p-0 mt-4 border rounded-lg md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0">
            <li className="mt-2 md:mb-0">
              <Link
                to="/app"
                className={getNavLinkClass("/app")}
                aria-current="page"
                onClick={closeMenu}
              >
                {t("navbar.links.home")}
              </Link>
            </li>
            <li className="mt-2">
              <Link
                to="/app/posts"
                className={getNavLinkClass("/app/posts")}
                onClick={closeMenu}
              >
                {t("navbar.links.posts")}
              </Link>
            </li>
            <li className="mt-2">
              <Link
                to="/app/leaderboard"
                className={getNavLinkClass("/app/leaderboard")}
                onClick={closeMenu}
              >
                {t("navbar.links.leaderboard")}
              </Link>
            </li>
            {!isLoggedIn ? (
              <div className="flex flex-col md:flex-row md:space-x-4">
                <li className="mb-2 md:mb-0">
                  <Link
                    to="/app/signin"
                    onClick={closeMenu}
                  >
                    <button className="relative inline-flex h-12 overflow-hidden rounded-full p-[1px] focus:outline-none focus:ring-2 focus:ring-slate-400 focus:ring-offset-2 focus:ring-offset-slate-50">
                      <span className="absolute inset-[-1000%] animate-[spin_2s_linear_infinite] bg-[conic-gradient(from_90deg_at_50%_50%,#E2CBFF_0%,#393BB2_50%,#E2CBFF_100%)]" />
                      <span className="inline-flex   h-full w-full cursor-pointer items-center justify-center rounded-full bg-gradient-to-l  from-[#c779e8] to-indigo-500 px-5  text-lg font-small text-white backdrop-blur-3xl">
                        {t("navbar.links.signin")}
                      </span>
                    </button>
                  </Link>
                </li>
                <li>
                  <Link
                    to="/app/signup"
                    onClick={closeMenu}
                  >
                    <button className="relative inline-flex h-12 overflow-hidden rounded-full p-[1px] focus:outline-none focus:ring-2 focus:ring-slate-400 focus:ring-offset-2 focus:ring-offset-slate-50">
                      <span className="absolute inset-[-1000%] animate-[spin_2s_linear_infinite] bg-[conic-gradient(from_90deg_at_50%_50%,#E2CBFF_0%,#393BB2_50%,#E2CBFF_100%)]" />
                      <span className="inline-flex   h-full w-full cursor-pointer items-center justify-center rounded-full bg-gradient-to-l  from-[#c779e8] to-indigo-500 px-5  text-lg font-small text-white backdrop-blur-3xl">
                      {t("navbar.links.signup")}
                      </span>
                    </button>
                    
                  </Link>
                </li>
              </div>
            ) : (
              <>
                <li className="mt-2">
                  <Link
                    to="/app/new-post"
                    className={getNavLinkClass("/app/new-post")}
                    onClick={closeMenu}
                  >
                    {t("navbar.links.newpost")}
                  </Link>
                </li>
                <li className="mt-2">
                  <Link to="/app/code" className={getNavLinkClass("/app/code")} onClick={closeMenu}>
                    {t("code")}
                  </Link>
                </li> 
                <li className="mt-2">
                  <Link
                    to="/app/profile"
                    className={getNavLinkClass("/app/profile")}
                    onClick={closeMenu}
                  >
                    {t("navbar.links.profile")}
                  </Link>
                </li>
                
                <li className="mt-2">
                  <Link
                    to="/app/fav"
                    className={getNavLinkClass("/app/fav")}
                    onClick={closeMenu}
                  >
                    {t("navbar.links.favorite")}
                  </Link>
                </li>
                <li className="mt-2">
                  <button
                    className="block py-2 px-3 rounded md:border-0 md:p-0 text-white md:hover:text-blue-500 hover:bg-gray-700 hover:text-white md:hover:bg-transparent w-full text-left"
                    onClick={handleLogout}
                  >
                    {t("navbar.links.logout")}
                  </button>
                </li>
              </>
            )}
          </ul>
        </div>
      </div>
    </nav>
  );
};

export default Navbar;

**Comment by naisargi17** [comment]
I just change the colour and add buttons for sigin and sigup .. Which modification you didn't get it from my code , can you point it out specifically?

**Comment by manikumarreddyu** [comment]
before changing   

         <li className="mt-2 md:mb-0">
              <Link to="/app" className={getNavLinkClass("/app")} aria-current="page" onClick={closeMenu}>
                Home
              </Link>
            </li>

after changing

            <li className="mt-2 md:mb-0">
              <Link
                to="/app"
                className={getNavLinkClass("/app")}
                aria-current="page"
                onClick={closeMenu}
              >
                {t("navbar.links.home")}
              </Link>
            </li>

**Comment by naisargi17** [comment]
this is not done by me .

**Comment by manikumarreddyu** [comment]
okay

**Pull request merged**
