### PR TITLE
feat: Updated Home Page UI, Added About US, Added Recent 6 Posts from pagination API successfully Issue 4

### LINKED ISSUE #4: Enhance Home page of the website
try not to modify the navbar and footer unnecessarily as merge conflicts may arise later.

image

There need to be added following 2 sections:
1. An about us section
2. Recent posts sections

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves[#4]

### Description

1. Updated HomePage UI.
2. Added About Us page with self made image without an copyright issues.
3. Added recent 6 posts from pagination api.
4. All process is done keeping responsiveness in mind.

### Related Issues
Fixes #4 

### Changes Made
Improvements in Home page UI.
New Features : About Us and Recent Posts sections.

### Screenshots

1. Hero Section.

image

2. About Us Section.

image

3. 6 latest Posts.

image

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
great work, just 2 things
1. about and hero images are too big, especially about image is over 5mb
2. remove vite.config.ts.timestamp file

**Comment by MeetDOD** [comment]
Okay i will do the changes !

**Comment by MeetDOD** [comment]
@VaibhavArora314 I had reduced the image size to KB's

**Review by Ultimateutkarsh11 — APPROVED** [review]
Great work @MeetDOD, the website looks much better now!

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by VaibhavArora314** [comment]
Resolve merge conflicts, rest is good

**Comment by MeetDOD** [comment]
@VaibhavArora314 Done 👍

**Comment by MeetDOD** [comment]
@VaibhavArora314 Done 👍

**Pull request merged**
