### PR TITLE
Changed Home Page code editor Section to responsive

### PR DESCRIPTION
**Pull request by manikumarreddyu**
# Pull Request

### Title

Changed Home Page code editor Section to responsive

### Description

Changed Home Page code editor Section to responsive

### Related Issues

fixes: #282 

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)

please check in preview

### Additional Notes

Footer

### CODE REVIEW

**Comment by manikumarreddyu** [comment]
hey @VaibhavArora314 please check it once

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
text-xs is too small

image

**Comment by manikumarreddyu** [comment]
hey @VaibhavArora314  @Ultimateutkarsh11 please review it once

**Comment by VaibhavArora314** [comment]
remove the sm:text-md class since they are anyways text-md

**Comment by manikumarreddyu** [comment]
> remove the sm:text-md class since they are anyways text-md

okay @VaibhavArora314

**Review by VaibhavArora314 — APPROVED** [review]

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Pull request merged**
