### PR TITLE
Fixed the FAQ section for mobile screen

### LINKED ISSUE #517: Fix FAQ section for Mobile screen
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

image

### Use Case

It shoudl be fixed to be visible properly on all screen sizes

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Utsavladia**
# Pull Request

### Title
Fixed the FAQ for mobile screen 

### Description
Made it look good for mobile screen

### Related Issues
Fixes #517 

### Changes Made
image

### Checklist 

- [x] I have tested the changes locally
- [ ] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Additional Notes

Footer

### CODE REVIEW

**Comment by VaibhavArora314** [comment]
Do you have a code formatter on? As it becomes hard to find the changes if you format the code.

**Comment by Utsavladia** [comment]
@VaibhavArora314 
Yes code formatter formated the code but anyways I have tested it is working fine.. and I'll turn it off for further contributions

**Review by VaibhavArora314 — APPROVED** [review]

**Review by akbatra567 — APPROVED** [review]

**Review by Ultimateutkarsh11 — CHANGES_REQUESTED** [review]
@Utsavladia kindly resolve the merge conflicts

**Comment by Utsavladia** [comment]
@Ultimateutkarsh11  
Resolved ✅

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Pull request merged**
