### PR TITLE
feat: Added category in homepage with sliding effect successfully issue 271

### LINKED ISSUE #271: [Feature Request]: Making beautiful category frontend
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Making separate page which showcase all the category available in style share. 
Integrating it with the issue #270 

### Use Case

UI

### Benefits

UX

### Add ScreenShots

image

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [#271 ]

### Description

1.  Added Marque package to add the effect and fetching the tags from the backend.
2.  Also user can click and naviagte to the tag page where all the posts is related to that tag.
3.  The design is responsive and can work in both light/dark mode.
4.  Takes the help of PR #270 

### Related Issues
Fixes #271 

### Changes Made
New features: Added category in homepage with sliding effect.

### Screenshots

image

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Comment by MeetDOD** [comment]
@VaibhavArora314 can you give anyone level 3 after evaluating the whole code 😄

**Comment by manikumarreddyu** [comment]
> @VaibhavArora314 can you give anyone level 3 after evaluating the whole code 😄

@MeetDOD great feature bro...it definitely deserves level 3..

**Review by VaibhavArora314 — COMMENTED** [review]
will review this after merging #286 since it is dependent on that

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
update the link route to /app/posts?tags=values

**Comment by MeetDOD** [comment]
> update the link route to /app/posts?tags=values

it is updated already !

image

can you tell me the name of the component where it is not labeled ?

**Comment by MeetDOD** [comment]
@VaibhavArora314 Check now !

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
image

on smaller devices, there is a lot of empty space on right space
probably due to the animation content going outside frame

**Comment by MeetDOD** [comment]
@VaibhavArora314 It's done 👍

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
