### PR TITLE
Feat: Added download report feature in comments, reactions and favorite in admin panel successfully issue 558

### LINKED ISSUE #558: [Feature Request]: Adding download report button for comments, favorites and reactions in admin panel
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will use the same approach that i used for the dashboard download report button.
So that the admin can use the report everywhere

### Use Case

Admin engagement

### Benefits

Admin enhancement

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [ #558 ]

### Description

1. In backend, I created 3 controllers and 3 routes which uses the Pdfkit to convert the prisma database data to pdf format.
2. In admin, I am getting the api created above and downloading the pdf via admin.
3. The design is responsive.

### Related Issues
Fixes #558 

### Changes Made
New feature:  Added download report feature in comments, reactions and favorite in admin panel.

### Screenshots

image

image

image

image

image

image

image

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Review by VaibhavArora314 — COMMENTED** [review]
resolve merge conflicts

**Comment by MeetDOD** [comment]
@VaibhavArora314 Done 👍

**Review by VaibhavArora314 — APPROVED** [review]

**Review by akbatra567 — APPROVED** [review]

**Comment by VaibhavArora314** [comment]
Resolve conflicts

**Comment by MeetDOD** [comment]
@VaibhavArora314 Done 👍

**Pull request merged**
