### PR TITLE
changed Navbar  to new version 

### PR DESCRIPTION
**Pull request by manikumarreddyu**
# Pull Request

### Title

changed Navbar  to new version 

### Description

changed Navbar  to new version 
### Related Issues

fixes: #229 
### Changes Made

1. navbar.tsx

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### CODE REVIEW

**Comment by manikumarreddyu** [comment]
hey @VaibhavArora314 check it once , and let me know any changes required.
Thank you!!

**Comment by VaibhavArora314** [comment]
if possible, restore the purple-blue variant. it looked better.

**Comment by VaibhavArora314** [comment]
https://github.com/VaibhavArora314/StyleShare/commit/3bfe618bd2cb5a3c3fd69f5d28ad88f2c2bdd890

I guess this was the commit in which the navbar was changed

**Comment by manikumarreddyu** [comment]
image
hey @VaibhavArora314 check it once , and let me know any changes required.
Thank you!!

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
