### PR TITLE
Feat: Added graphs(Line, Bar, Bubble, Scatter) for admin successfully issue 367

### LINKED ISSUE #367: [Feature Request]: Adding separate graphs page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

1. In this i will create a graph page which will visualize all the api used in the dashboard in the form of graph.
2. So, that i will become easy for admin to visualize it and maintain the site proper.
3.  will use chart.js to achieve this feature.
4. Other libraries too..

### Use Case

Visualization

### Benefits

Admin friendly

### Add ScreenShots

Eg:

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves[#367 ]

### Description

1.  In admin backend, I created a controller called getgraphsstatus and it's routes also this api give the created date of any instance in style share i.e users, posts, comments, favorities, contactmessages and reactions.
2.  In admin frontend, I created a Graph page also updated the sidebar and router also.
3.  In Graph page i had used chartjs and react-chartjs-2 and I am fetching the data from the api and converting it into four graph format for admin.
4.  The design is responsive in all devices.

### Related Issues
Fixes #367 

### Changes Made
New feature: Added graphs(Line, Bar, Bubble, Scatter) for admin.

### Screenshots

image

image

image

image

image

image

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
image

**Comment by MeetDOD** [comment]
> image image

@VaibhavArora314 in my local it is fetching in deployment why it is not rendering it ?

**Comment by VaibhavArora314** [comment]
@MeetDOD 
image

**Comment by VaibhavArora314** [comment]
the old records do not have the createdAt field that's why this error is coming I guess

**Comment by MeetDOD** [comment]
Ya I got it so what to do now ?

**Comment by MeetDOD** [comment]
can we just create new data or something like you delete the reactions from the database that will not heart anything or else we use other approach if you have !

**Comment by VaibhavArora314** [comment]
> can we just create new data or something like you delete the reactions from the database that will not heart anything or else we use other approach if you have !

I will update the database, give me some time

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
Is it possible to add a msg below each graph or label the x-y axis to better understand what the graph is about?

**Comment by MeetDOD** [comment]
> Is it possible to add a msg below each graph or label the x-y axis to better understand what the graph is about?

@VaibhavArora314 I label the graphs at x and y axis respectively, this library has built in feature 😄

**Comment by VaibhavArora314** [comment]
image

what are the two charts below for?

**Comment by MeetDOD** [comment]
> image
> 
> what are the two charts below for?

So, every api like user,post,reaction all of them i created four graphs, line,bar,bubble,scatter respectively.
so the above two are:
line | bar
bubble | scatter

like this 👍

**Comment by VaibhavArora314** [comment]
> > image
> > what are the two charts below for?
> 
> So, every api like user,post,reaction all of them i created four graphs, line,bar,bubble,scatter respectively. so the above two are: line | bar bubble | scatter
> 
> like this 👍

I don't think bubble and scatter graphs have much use in most cases with respect to time for our application. Can you please remove them, rest is looking good.

**Comment by MeetDOD** [comment]
> > > image
> > > what are the two charts below for?
> > 
> > 
> > So, every api like user,post,reaction all of them i created four graphs, line,bar,bubble,scatter respectively. so the above two are: line | bar bubble | scatter
> > like this 👍
> 
> I don't think bubble and scatter graphs have much use in most cases with respect to time for our application. Can you please remove them, rest is looking good.

It will look nice when the data will be populated also it will be easy to admin to visualize, But never mind i removed it @VaibhavArora314 👍

**Comment by MeetDOD** [comment]
> Deployment failed with the following error:
> 
> ```
> The provided GitHub repository does not contain the requested branch or commit reference. Please ensure the repository is not empty.
> ```

@VaibhavArora314 what is this ?

**Comment by VaibhavArora314** [comment]
Can't find anything in vercel logs and the website is also not updated. It's probably a vercel error, let me look into it.

> > Deployment failed with the following error:
> > ```
> > The provided GitHub repository does not contain the requested branch or commit reference. Please ensure the repository is not empty.
> > ```
> 
> @VaibhavArora314 what is this ?

**Comment by VaibhavArora314** [comment]
Most probably you will have to create a new pull request as vercel is not detecting up changes in this PR.

**Comment by MeetDOD** [comment]
> Most probably you will have to create a new pull request as vercel is not detecting up changes in this PR.

🗿

**Comment by MeetDOD** [comment]
> Most probably you will have to create a new pull request as vercel is not detecting up changes in this PR.

Ok I will do that give me a minute

**Comment by MeetDOD** [comment]
Now it is checking/working when i cratead a new PR 🗿

**Comment by VaibhavArora314** [comment]
> Now it is checking/working when i cratead a new PR 🗿

Lmao, anyways closing this now since #425 is created

**Pull request closed without merging**
