### PR TITLE
feat: Added follow/unfollow feature successfully Issue 250

### LINKED ISSUE #250: [Feature Request]: Follow/Unfollow feature in style share.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

WIth this feature user can follow their favorite design creator and engage with them.

### Use Case

UI

### Benefits

UX

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [#250 ]

### Description

1.  In backend, In Prisma added new Follow schema and added in following and followers in User.
2.  Created routes and controllers for followUserController, unfollowUserController and checkFollowStatusController in User also updated getPostcontroller to get total followers of a user.
3.  In frontend, Fetched and get the follow api in Post.tsx, UserProfile and in showprofile also showing total followers to their profile.
4.  Also a user need to logged In and verified to access this feature.
5.  Also a user cannot follow himself.
6.  All design is responsive.

### Related Issues
Fixes #250 

### Changes Made
New features: Added follow/unfollow feature successfully.

### Screenshots

image

###Video

https://github.com/VaibhavArora314/StyleShare/assets/120380073/bc3f6a9c-69b1-4ca6-a4c4-4cd581e5fab3

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Comment by MeetDOD** [comment]
@VaibhavArora314 You and me are pushing to vercel same time, i want to pull again and again now it's done 💀

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 You and me are pushing to vercel same time, i want to pull again and again now it's done 💀

Lol, I was just refactoring the code.
Anyways, this looks good, give me some time to completely review it.

**Comment by MeetDOD** [comment]
> > @VaibhavArora314 You and me are pushing to vercel same time, i want to pull again and again now it's done 💀
> 
> Lol, I was just refactoring the code. Anyways, this looks good, give me some time to completely review it.

No, worries I was keep seeing my files where is error than i came to my fork and says @VaibhavArora314 commited 0 sec ago 🗿

**Comment by VaibhavArora314** [comment]
Resolve merge conflicts, rest is looking good.

**Comment by MeetDOD** [comment]
@VaibhavArora314 you merge #267 pr then i will pull in this and then push it to avoid conflicts .

**Comment by MeetDOD** [comment]
@VaibhavArora314 can you show me the error logs, I don't know where the error is 🤔

**Comment by VaibhavArora314** [comment]
image

**Comment by MeetDOD** [comment]
@VaibhavArora314  Done 👍

**Comment by VaibhavArora314** [comment]
image

followers is not readable in light mode

**Comment by MeetDOD** [comment]
> image
> 
> followers is not readable in light mode

Okay I will do the changes

**Comment by MeetDOD** [comment]
@VaibhavArora314 I applied the theme wherever there is a follow/unfollow as well as in button 🙂

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
