### PR TITLE
feat: Added mark components as favorites and unfavorites feature successfully issue 123

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [#123 ]

### Description

1.   In backend: I created a new prisma schema for storing fav/unfav posts in database.
2.   Also created routes and controller for 3 operations, -Favorite -Unfavorite -FetchFavorite posts respectively.
3.   In Frontend fetch and posting operation is done, new file is created called Favorite where all fav posts are fetched.
4.   By clicking heart icon user can fav/unfav a post.

### Related Issues
Fixes #123 

### Changes Made
New features: Adding mark components as favorites/unfavorities.

### Screenshots

image 

### Video Demo

https://github.com/VaibhavArora314/StyleShare/assets/120380073/817a29d3-7105-4fbd-b183-a5090722b053

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Comment by MeetDOD** [comment]
@VaibhavArora314 Tell me other features you like to see in future >_<

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
1. in getFavoritePostsController, get userId from UserAuthRequest instead of params
2. there is no need to send a me request separately in the Favorite.tsx, The userState already in store/atoms

**Comment by MeetDOD** [comment]
@VaibhavArora314 Done the changes as requested !

**Comment by MeetDOD** [comment]
also @VaibhavArora314 assign me issue #126 :)

**Comment by VaibhavArora314** [comment]
> also @VaibhavArora314 assign me issue #126 :)

I have asked the assigned person, if he is inactive or not working on it anymore then you can work on it

**Comment by MeetDOD** [comment]
> remove /:id from the route to get favorite posts

then how i will able to fetch their fav posts ?

**Comment by MeetDOD** [comment]
@VaibhavArora314 sir, I checked and tested the whole feature and it's working fine ...

**Review by VaibhavArora314 — APPROVED** [review]
Ok, I will later separate the routes to avoid conflicts.

**Pull request merged**
