### PR TITLE
Feat: Added post search suggestion when search on searchbar successfully issue 586

### LINKED ISSUE #586: [Feature Request]: Shoowing search suggesstion when typing on search bar
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

It will help user to browse fastly and efficiently.

### Use Case

UI/UX

### Benefits

Fast search

### Add ScreenShots

image

eg:

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [ #586 ]

### Description

1. In backend, I created the route and controller for getting searchQuery and suggest to user.
2. In frontend, I am fetching the api in the usePosts and then calling the function in the Posts component.
3. While writing on the search bar with the help of ul the user can see the dropdown and click on any it will see that posts.
4. The design is responive and work in both light/dark mode respectively.

### Related Issues
Fixes #586 

### Changes Made
New feature: Added post search suggestion when search on searchbar.

### Screenshots

image

### Video

https://github.com/user-attachments/assets/efa1c7d5-b06f-419d-90c0-44acb37dbcd7

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Comment by MeetDOD** [comment]
@VaibhavArora314 Please give level 3 if possibe after evaluation due to frontend + backend integration 👍

**Review by VaibhavArora314 — COMMENTED** [review]
Currently, a request is sent for every letter typed or removed from the thsearch input. Maybe you can use a setTimeout to call the API after like 300ms and if the user changes something in the search query within those 300ms, then you can clear the previous timeout and set a new timeout for the API call after 300ms.

**Comment by VaibhavArora314** [comment]
If it's too much then tell me here, I will merge it under level 2.

**Comment by MeetDOD** [comment]
> If it's too much then tell me here, I will merge it under level 2.

Merge with level 2 only then 👍

**Comment by MeetDOD** [comment]
> Currently, a request is sent for every letter typed or removed from the search input. Maybe you can use a setTimeout to call the API after like 300ms and if the user changes something in the search query within those 300ms, then you can clear the previous timeout and set a new timeout for the API call after 300ms. This process of clearing timeout will keep on going on until the user stops changing the search query and then results will be shown.

Nice optimal solution, I am doing it @VaibhavArora314 👍

**Comment by MeetDOD** [comment]
@VaibhavArora314 Done with the changes as requested 💯

**Review by VaibhavArora314 — COMMENTED** [review]
Looks Good, just one minor change
when no suggestions available don't show this empty box
image

**Comment by MeetDOD** [comment]
> Looks Good, just one minor change when no suggestions available don't show this empty box image

Noted 👍

**Comment by MeetDOD** [comment]
@VaibhavArora314 Done 💯

**Comment by VaibhavArora314** [comment]
Comment axios default baseurl logic

**Comment by MeetDOD** [comment]
Opps, In hurry I totally forgot about that, my bad :

**Comment by MeetDOD** [comment]
@VaibhavArora314 please merge my PRS only 2 hours is remaining Thank YOU 👍

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by VaibhavArora314** [comment]
@akbatra567 kindly review and merge this as soon as possible

**Review by akbatra567 — APPROVED** [review]

**Pull request merged**
