### PR TITLE
ADDED Trending posts 

### PR DESCRIPTION
**Pull request by manikumarreddyu**
# Pull Request

### Title

ADDED Trending posts 

### Description

It gives top 6 posts based on user reaction count

### Related Issues

Fixes: #248 

### Changes Made

added new compnent 
1. TrendingPosts.tsx

2.getTrendingPostsController  (in post/controller.ts)

some other small changes

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)

It is better to see in preview

### Additional Notes

nothing
Footer

### CODE REVIEW

**Comment by manikumarreddyu** [comment]
@MeetDOD  can you please help me why i am getting deployment error

**Comment by MeetDOD** [comment]
> @MeetDOD can you please help me why i am getting deployment error

Bro I can't, only @VaibhavArora314 can see the logs and tell he has the access/deployed with his vercel account 👍

**Comment by manikumarreddyu** [comment]
> > @MeetDOD can you please help me why i am getting deployment error
> 
> Bro I can't, only @VaibhavArora314 can see the logs and tell he has the access/deployed with his vercel account 👍

okay @MeetDOD

**Comment by manikumarreddyu** [comment]
hey @VaibhavArora314 can you please help with me with deployment failure
i my local it is working fine but deployment keeps failing

**Comment by manikumarreddyu** [comment]
DONT MERGE THE PR

**Comment by manikumarreddyu** [comment]
https://github.com/VaibhavArora314/StyleShare/assets/133508962/34db5b1d-1293-4d2e-86db-1157b4738a9e

**Comment by manikumarreddyu** [comment]
I think it is a level 3 issue...it is very hard... @VaibhavArora314

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
rather than creating a seperate page for it, you can add a filter on the posts page where user can select to see post by creation date or popularity

**Comment by manikumarreddyu** [comment]
Okay @VaibhavArora314

**Pull request closed without merging**
