### PR TITLE
custom cursor added (issue 191)

### PR DESCRIPTION
**Pull request by chaanakyaaM**
# Pull Request

### Title

Custom Cursor

### Description

Custom cursor added to the website.

### Related Issues

#191

### Changes Made

I have added custom interactive cursor.

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Additional Notes

Footer

### CODE REVIEW

**Comment by chaanakyaaM** [comment]
Kindly let me know if there are any changes to be made.

**Comment by VaibhavArora314** [comment]
Don't know why but I am unable to scroll down. Also, instead of writing a script, is it possible to create a component for this and import it in App.tsx

**Comment by manikumarreddyu** [comment]
> Don't know why but I am unable to scroll down. Also, instead of writing a script, is it possible to create a component for this and import it in App.tsx

yeah it is not working properly

**Comment by chaanakyaaM** [comment]
ok, i will fix it.

**Comment by chaanakyaaM** [comment]
I have fixed the page not scrolling bug, but i couldn't create a compounet for this cursor effect.

**Comment by chaanakyaaM** [comment]
would you like to merge this PR ???

**Comment by VaibhavArora314** [comment]
> would you like to merge this PR ???

I was not on my laptop before so wasn't able to test the cursor

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
