### PR TITLE
About Us Page Text Colour Changed

### PR DESCRIPTION
**Pull request by poseidonsanket**
# Pull Request

### Title
Changed Some Text Colour in About Us page to white to make it more visible

### Description
Changed Some Text Colour in About Us page to white to make it more visible

### Related Issues
Fixes - #133 

### Changes Made
Added styling as "text-white"

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)
Capture

### Additional Notes

Footer

### CODE REVIEW

**Comment by poseidonsanket** [comment]
@VaibhavArora314 please review

**Comment by MeetDOD** [comment]
it is white text only in the deployed live webapp ? there is not black text anywhere !
so, why this changes ?

image

**Comment by poseidonsanket** [comment]
@MeetDOD when You go to about us page from footer link you will see black text
Please try that

**Comment by MeetDOD** [comment]
Okay i think that in the home page it's giving error :)

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
