### PR TITLE
feat: Added a 404 page not found route in frontend Successfully Issue 105

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [#105 ]

### Description

1. Added Image in assests of size ~ 300kb.
2. Added Route and text in NotFoundPage file.

### Related Issues
Fixes: #105 

### Changes Made
New feature: Added a 404 page not found route in frontend.

### Screenshots

image

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
looks good, resolve merge conflicts and did u push toast commits in this?

**Comment by MeetDOD** [comment]
@VaibhavArora314 it's Done :), and also it has toast feature also.

**Review by VaibhavArora314 — COMMENTED** [review]
everything is great for not found route page, just that the error/verification error state logic has to be added back in Profile (part of toast pr)

**Comment by MeetDOD** [comment]
okay, got it

**Comment by VaibhavArora314** [comment]
@MeetDOD resolve merge conflicts rest is good.

**Comment by MeetDOD** [comment]
😭

**Comment by MeetDOD** [comment]
@VaibhavArora314 have a look !

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
