### PR TITLE
Feat: Added preloader in style share successfully issue 412

### LINKED ISSUE #412: [Feature Request]: Adding preloader to  the  website.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Using the gsap  animation and react framer motion.

### Use Case

Will enhance the UI  of website.

### Benefits

_No response_

### Add ScreenShots

https://github.com/VaibhavArora314/StyleShare/assets/138770813/a33d5540-887c-426a-8329-6c3ea1275c89

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request resolves [ #412 ]

### Description

1. In frontend, I set the timmer for 5 second so that the animation fully completed.
2. I created 2 files i.e Preloader.tsx and its .css.
3. The design is responsive.

### Related Issues
Fixes #412 

### Changes Made
New feature: Added preloader in style share.

### Screenshots

image

### Video

https://github.com/user-attachments/assets/74037ee4-f776-45c3-88c6-3da0549532f2

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
Great work, just one thing can most of the styling be implemented using tailwind to maintain consistency

**Comment by MeetDOD** [comment]
> Great work, just one thing can most of the styling be implemented using tailwind to maintain consistency

Okay I will figure it out I will use as much as tailwind css only to stick to consistency of style share !

**Comment by MeetDOD** [comment]
@VaibhavArora314 Done !

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by MeetDOD** [comment]
@Ultimateutkarsh11 please give level 2 if possible after complete evaluation 👍

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Pull request merged**
