### PR TITLE
feat: Combined the feature of like/dislike with the reaction feature successfully issue 252

### LINKED ISSUE #252: [Feature Request]: Combining like/dislike with reactions in style share
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This feature will add the both functionality like as well as dislike also for other users expressions they can react also for a particular post.
So, the basic scenario we can take is of the linkedin post reaction from users.
Therefore, the same approach will be taken to implement the combo of both the feature.

### Use Case

UI/UX

### Benefits

User engagement.

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [#252 ]

### Description

1. Removed the like/dislike routes and controllers from the backend and created a fresh 4 api's for reactions.
2. API's are reactToPostController,removeReactionController, getUserReaction, getAllreaction and their respective routes. 
3. In frontend, I created ReactionButtons.tsx which post and get the reaction which allow user to do reactions.
4. In PostCard I fetched all the reaction by all the users and sum it up to show total and the emoji will show only one time each.
5. I created five emoji exactly like linkedin also ~ same colors => 'Like' | 'Celebrate' | 'Support' | 'Love' | 'Insightful' | 'Funny'.
6. The design is simple and easy to use by any user.
7. User most be a verified user and also logged In to the application.
8. By default if user click on button it will trigger like button or he/she can choose from various emoji's also again click it will remove the emoji.

### Related Issues
Fixes #252 

### Changes Made
New features: Combined the feature of like/dislike with the reaction feature

### Screenshots

image

### Video

https://github.com/VaibhavArora314/StyleShare/assets/120380073/75f601fe-32f5-4952-8722-6104457c87bf

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Comment by MeetDOD** [comment]
@VaibhavArora314 it's done finally 😭 can you show me why the deployment failed ?

**Comment by MeetDOD** [comment]
@VaibhavArora314 It's Done 😄, please merge this PR first because their are many changes done, if you merge other PR than it will lead to huge conflicts because their are many changes done.

**Review by VaibhavArora314 — COMMENTED** [review]
Just 2 minor changes,
1. show post reactions like done on post card on post page also 
image
2. If userpostinteraction model is not used can we delete it?

**Comment by MeetDOD** [comment]
@VaibhavArora314 done both the changes as requested.

image

**Comment by MeetDOD** [comment]
Hello, @VaibhavArora314 any updates 😢

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by VaibhavArora314** [comment]
> Hello, @VaibhavArora314 any updates 😢

sorry for the late response. looks good to me now.

**Pull request merged**
