### PR TITLE
feat: Added customizing with AI should also take js code and customize it with css successfully Issue 266

### LINKED ISSUE #266: Customizing with AI should also take js code if present in actual component and return updated js code accordingly
image

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [#266 ]

### Description

1.  Removed ai controller and routes + packages from the backend.
2.  Implement all functionality in the frontend at CustomizeWithAi.tsx. so, that it will not give stress to the backend and now the request timeout problem will get solved in deployed webapp.
3.  Updated .env.example in frontend as well as in backend also add .env in frontend gitignore. for safety.
4.  Now User can give JS + HTML code in input and gemini will give output according to prompt provided by the users.

### Related Issues
Fixes #266 

### Changes Made
New features: Added customizing with AI should also take js code and customize it with css successfully.

### Screenshots

image

### Video

https://github.com/VaibhavArora314/StyleShare/assets/120380073/995dbb40-47f2-4132-b6bb-9295651e34a3

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Comment by MeetDOD** [comment]
@VaibhavArora314 I think i did the same mistake as of previous all the push of follow/unfollow is also here 😭, sorry bruh first you merge #250 then do this if any problem i will do it 🙂/😢

**Review by VaibhavArora314 — COMMENTED** [review]
looking good overall, give me some time to completely review this.
in the meanwhile, just one suggestion keep the generation logic in backend since providing such secrets on frontend can be risky. 

also to remove the time constraint problem maybe we can do one thing, when user customizes post, a modification is created and stored in db then after 30 sec it fetches from db. this way we can counter the timeout request problem.

**Comment by MeetDOD** [comment]
> looking good overall, give me some time to completely review this. in the meanwhile, just one suggestion keep the generation logic in backend since providing such secrets on frontend can be risky.
> 
> also to remove the time constraint problem maybe we can do one thing, when user customizes post, a modification is created and stored in db then after 30 sec client fetches from backend. this way we can counter the timeout request problem.

It is safe unless and untill user will not secret key, also it will stress the backend very much.

1. old

react => node => gemini => node => react

2. new

react => gemini => react

**Comment by VaibhavArora314** [comment]
> > looking good overall, give me some time to completely review this. in the meanwhile, just one suggestion keep the generation logic in backend since providing such secrets on frontend can be risky.
> > also to remove the time constraint problem maybe we can do one thing, when user customizes post, a modification is created and stored in db then after 30 sec client fetches from backend. this way we can counter the timeout request problem.
> 
> It is safe unless and untill user will not secret key, also it will stress the backend very much.
> 
> 1. old
> 
> react => node => gemini => node => react
> 
> 2. new
> 
> react => gemini => react

I get what you are trying to say but there are other issues also with passing env variables in frontend since we are serving the build of website through express server

**Comment by MeetDOD** [comment]
> > > looking good overall, give me some time to completely review this. in the meanwhile, just one suggestion keep the generation logic in backend since providing such secrets on frontend can be risky.
> > > also to remove the time constraint problem maybe we can do one thing, when user customizes post, a modification is created and stored in db then after 30 sec client fetches from backend. this way we can counter the timeout request problem.
> > 
> > 
> > It is safe unless and untill user will not secret key, also it will stress the backend very much.
> > 
> > 1. old
> > 
> > react => node => gemini => node => react
> > 
> > 2. new
> > 
> > react => gemini => react
> 
> I get what you are trying to say but there are other issues also with passing env variables in frontend since we are serving the build of website through express server

Ohh ! okay i got it now the build is with the express okay so, i will leave the code to default as previous and I will add just JS code for customization GOT IT 👍

**Comment by MeetDOD** [comment]
@VaibhavArora314 done check it once 🙂

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
