### PR TITLE
Added borders to testimonials. Issue number #484

### LINKED ISSUE #484: [Feature Request]: Outlined cards for user reviews.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The user reviews can be enclosed in card-like blocks.

image

### Use Case

It will enhance the UI as the changing reviews will be more visible and visually appealing.

Examples for reference:

image

image

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by TaeMochi12**
# Pull Request

### Title
Added borders to testimonials. Issue number #484

### Description
Added borders for testimonials in boht light and dark mode for better readability and appearance.

### Related Issues
Fixes #484

### Changes Made
Added some tailwind classes for borders.

### Checklist 

- [x] I have tested the changes locally
- [ ] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)
Screenshot 2024-08-01 003733
Screenshot 2024-08-01 003747
Screenshot 2024-08-01 003911
Screenshot 2024-08-01 003935

### Additional Notes

Footer

### CODE REVIEW

**Comment by TaeMochi12** [comment]
@VaibhavArora314 I've completed the issue #484 . Kindly review the PR.

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
Currently, testimonials are being fetched from the backend and you have removed that logic. Kindly look into that.

**Comment by TaeMochi12** [comment]
Ok sir

**Comment by TaeMochi12** [comment]
@VaibhavArora314 Done with the requested changes. Kindly review it once.

**Review by akbatra567 — APPROVED** [review]

**Pull request merged**
