### PR TITLE
feat: Added Download as zip button feature successfully issue 196

### LINKED ISSUE #196: [Feature Request]: Download code as zip button.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a button near the code snippet where when user click on it the code in the code snippet of that post will get downloaded in their machine.

Later they can do whatever they want with the zip.

### Use Case

User comfort

### Benefits

User flexibility

### Add ScreenShots

image

here i will give the Download as zip button.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [#196 ]

### Description

1.  Downloaded the npm packages npm install jszip file-saver which help in convert to zip and save to the user system.
2.  User have to login to download the code.
3.  Both code i.e html as well as js is compressed in the zip.
4.  Changes is done in Post.js for download and in PostCodeWithPreview for css.

### Related Issues
Fixes #196 

### Changes Made
New features: Added Download as zip button feature.

### Screenshots

image

image

image

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Comment by MeetDOD** [comment]
@VaibhavArora314 I think In the deployed webapp instead of test posts we should post some real content now because the webapp is quite look nice 😄

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 I think In the deployed webapp instead of test posts we should post some real content now because the webapp is quite look nice 😄

yes, I am planning to clear the posts from the database. also, I will take some time to review the pr.

**Comment by VaibhavArora314** [comment]
looks good to me, just resolve conflicts

**Comment by MeetDOD** [comment]
> looks good to me, just resolve conflicts

Done @VaibhavArora314

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
