### PR TITLE
Feat: Added graphs(Line, Bar, Bubble, Scatter) for admin successfully issue 367

### LINKED ISSUE #367: [Feature Request]: Adding separate graphs page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

1. In this i will create a graph page which will visualize all the api used in the dashboard in the form of graph.
2. So, that i will become easy for admin to visualize it and maintain the site proper.
3.  will use chart.js to achieve this feature.
4. Other libraries too..

### Use Case

Visualization

### Benefits

Admin friendly

### Add ScreenShots

Eg:

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves[#367 ]

### Description

1.  In admin backend, I created a controller called getgraphsstatus and it's routes also this api give the created date of any instance in style share i.e users, posts, comments, favorities, contactmessages and reactions.
2.  In admin frontend, I created a Graph page also updated the sidebar and router also.
3.  In Graph page i had used chartjs and react-chartjs-2 and I am fetching the data from the api and converting it into four graph format for admin.
4.  The design is responsive in all devices.

### Related Issues
Fixes #367 

### Changes Made
New feature: Added graphs(Line, Bar, Bubble, Scatter) for admin.

### Screenshots

image

image

image

image

image

image

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Comment by MeetDOD** [comment]
@VaibhavArora314 check now any problem is there 👍

**Review by VaibhavArora314 — APPROVED** [review]

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by MeetDOD** [comment]
> Approved. @MeetDOD, could you resolve merge conflicts ?

Done 👍

**Comment by MeetDOD** [comment]
@akbatra567 please add level label also

**Comment by MeetDOD** [comment]
@Ultimateutkarsh11 @VaibhavArora314 please add level label 🙏

**Pull request merged**
