### PR TITLE
feat: Added route name on every tab successfully Issue 321

### LINKED ISSUE #321: [Feature Request]: Adding name on every tab while navigating through pages
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In this issue i will create a document.title and it will show on the tab every page user go on for example: if in posts page it will show style share | posts, at login style share | login like that in every page respectively.

### Use Case

UI

### Benefits

UX

### Add ScreenShots

current:

image

example:

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [#321 ]

### Description

1. I put the tab name on every possible places with the help of document.title feature.
2. With this user can see the tabs information easily and navigate seamlessly across the platform.
3. Used emoji's and fun text to make it interactive and user friendly.

### Related Issues
Fixes #321 

### Changes Made
New features: Added route name on every tab.

### Screenshots

1. Home Page 

image

2. Posts Page

image

3. Leaderboard

image

and similarly for the rest of them.

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
resolve merge conflicts. also, did you push changes of the categories pull request?

**Comment by MeetDOD** [comment]
> resolve merge conflicts. also, did you push changes of the categories pull request?

@VaibhavArora314 I keep on forgotting about it, sorry my bad i merge category also 😢

**Comment by MeetDOD** [comment]
Hey @VaibhavArora314 can you tell me how should i work on that admin like i should create all the api in the backend only and for frontend i have to put all in admin folder is that right ?

**Comment by MeetDOD** [comment]
@VaibhavArora314 Done 👍

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by VaibhavArora314** [comment]
> Hey @VaibhavArora314 can you tell me how should i work on that admin like i should create all the api in the backend only and for frontend i have to put all in admin folder is that right ?

you should create a separate route for them like /api/admin/v1/<endpointname> for admin routes

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by MeetDOD** [comment]
> > Hey @VaibhavArora314 can you tell me how should i work on that admin like i should create all the api in the backend only and for frontend i have to put all in admin folder is that right ?
> 
> you should create a separate route for them like /api/admin/v1/ for admin routes

I got that but I will create all API in backend folder only na and for frontend in admin folder ?

**Comment by VaibhavArora314** [comment]
> > > Hey @VaibhavArora314 can you tell me how should i work on that admin like i should create all the api in the backend only and for frontend i have to put all in admin folder is that right ?
> > 
> > 
> > you should create a separate route for them like /api/admin/v1/ for admin routes
> 
> I got that but I will create all API in backend folder only na and for frontend in admin folder ?

yes backend will remain in the same folder, only the frontend for admin will be in separate folder

**Pull request merged**
