### PR TITLE
Css update

### LINKED ISSUE #157: [Feature Request]: Enhancing Css of "new post" page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Screenshot (993)

The styling of this page is not very impressive. I want to update it and make it more user-friendly.

### Use Case

It will make the web page more user-friendly and impressive.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by asthanegi14**
# Pull Request

### Related Issues

Fixes #157 

### Checklist 

- [x] I have tested the changes locally
- [ ] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)

page before updates 

Screenshot (1001)

Page after updates 

Screenshot (1002)

Screenshot (1004)

### CODE REVIEW

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
for larger screens, you can increase the width of the component 
also decrease the width of the add tag button on large screens, it taking half of the width

**Comment by asthanegi14** [comment]
> for larger screens, you can increase the width of the component also decrease the width of the add tag button on large screens, it taking half of the width

I will consider the changes required but can you specify how much width you prefer for a large screen @VaibhavArora314 ?

**Comment by asthanegi14** [comment]
Is this much width okay with you @VaibhavArora314 ?
 
Screenshot (1006)

Screenshot (1008)

**Comment by VaibhavArora314** [comment]
> Is this much width okay with you @VaibhavArora314 ?
>  
> Screenshot (1006)
> 
> Screenshot (1008)
> 

Looks good just push the changes, I will merge this

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
