### PR TITLE
fixed sizing for mobile screen

### LINKED ISSUE #190: FIX for mobile screen
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The Menu of top dissappear on hero image expand and the whole website become small in size as this image expand and goes out of screen.

### Use Case

It should be fixed to enhnace the user experience.

### Benefits

_No response_

### Add ScreenShots

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Utsavladia**
# Pull Request

### Title
Fixed hero sizing for mobile screen 

### Description
Fixed to have a proper sizing on mobile screen and the typing effect.

### Related Issues
Fixes #190 

### Changes Made
changed the sizing of text in typing effect to keep inside the screen for small screen size.

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)

image

### Additional Notes

Footer

### CODE REVIEW

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
image

heading looking smaller than text in some cases

**Comment by Utsavladia** [comment]
@VaibhavArora314 
Made it responsive for all sizes to look good.
image

**Comment by VaibhavArora314** [comment]
image
it looks better but some text of header is getting cut at top, maybe you can increase the height

**Comment by Utsavladia** [comment]
@VaibhavArora314 
fixed the line height issue and aligned the "|" symbol at center to stay in line of text.

image

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
