### PR TITLE
feat: Added edit profile in profile section cards successfully issue 195

### LINKED ISSUE #195: [Feature Request]: Edit button on profile section.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The Edit feature is fine, but it show when a user go inside the post by clicking on the read more button.
I want to add edit button near the delete button so that user will have a full control over his/her profile.

### Use Case

User enhancement 

### Benefits

user engagement

### Add ScreenShots

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [#195 ]

### Description

1.  I created a separate route as /posts/edit/:id where i am redireting owner of the post to edit the post.
2.  Also I added a edit button on the every card.
3.  I tested it and it is working properly.
4.  Responsive design.

### Related Issues
Fixes #195 

### Changes Made
New features: Added edit profile in profile section cards.

### Screenshots

image

image

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Comment by VaibhavArora314** [comment]
Looks good, but why is types/file-saver added in dependency? I mean I cant find where is it being used.

**Comment by MeetDOD** [comment]
@VaibhavArora314 my bad i had implemented that download as zip feature than you told it's not needed. but, i did npm uninstall but it trace remain init like that 😅

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 my bad i had implemented that download as zip feature than you told it's not needed. but, i did npm uninstall but it trace remain init like that 😅

Try doing `npm uninstall @types/file-saver`

**Comment by MeetDOD** [comment]
Okay

**Comment by MeetDOD** [comment]
@VaibhavArora314 done with the changes, please give the gssoc label 😄

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
In post, if user presses edit it should redirect to edit endpoint
Can you please seperate the edit logic from post page?

**Comment by MeetDOD** [comment]
@VaibhavArora314 you mean like i implemented on that card edit to redirect to /edit/:id like that ?

**Comment by MeetDOD** [comment]
@VaibhavArora314 I understood your query and implemented the same, if changes needed just tell me anytime 😄

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
the form is updated, even when i press cancel button

**Comment by MeetDOD** [comment]
> the form is updated, even when i press cancel button

In current website the same issue is appearing i think the problem is with who created this feature not from my side, i haven't changed any logic in the code @VaibhavArora314

**Comment by VaibhavArora314** [comment]
> > the form is updated, even when i press cancel button
> 
> In current website the same issue is appearing i think the problem is with who created this feature not from my side, i haven't changed any logic in the code @VaibhavArora314

ok I am merging this and will look into why is it causing that

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
