### PR TITLE
Added Margin Bottom for contact section

### LINKED ISSUE #545: [Bug]: Not Proper margin in contact form in bottom.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

image

I will give it some margin from bottom so boarder of that contact form from down side visible properly.

### Expected behavior

NA

### Add ScreenShots

NA

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by zalabhavy**
# Pull Request

### Title

Not Proper margin in contact form in bottom. 

### Description

Just added proper margin bottom for contact section.

### Related Issues

Fixes #545

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)

image

### CODE REVIEW

**Comment by zalabhavy** [comment]
@VaibhavArora314 @Ultimateutkarsh11 @akbatra567 Please check it and merge !

Thank You !

**Review by akbatra567 — COMMENTED** [review]
Hey @zalabhavy, 
Could you make a video of where the issue was, when I verify from current and changed version I don't see much difference and not able to find the issue with margin ?

Current: 
Screenshot 2024-08-02 at 09 49 32



Change:
Screenshot 2024-08-02 at 09 49 47

**Comment by zalabhavy** [comment]
@akbatra567 This issue was in chrome browser.

**In Chrome** 

image

**After In Chrome**

image

**Comment by akbatra567** [comment]
@zalabhavy, Tried with chrome. Same no issue. Could you share your screen resolution ? 

P.S. I checked with a lower height and then I was kind of able to reproduce. Need to verify the same.

**Review by VaibhavArora314 — APPROVED** [review]

**Review by akbatra567 — APPROVED** [review]

**Pull request merged**
