### PR TITLE
FEAT:  Light mode/Dark mode  successfully added

### PR DESCRIPTION
**Pull request by manikumarreddyu**
# Pull Request

### Title

Light mode/Dark mode  successfully added

### Description

Light mode/Dark mode  successfully added

### Related Issues

Fixes : #115 

### Changes Made

1. useTheme hook created in hooks
2. many changes are made

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)

just see the preview

### CODE REVIEW

**Comment by manikumarreddyu** [comment]
hey @VaibhavArora314 check it once , and let me know any changes required.


DONT MERGE THE PR @VaibhavArora314 
because i have commented in mant lines 
if you are okay with the changes then update me , i will make any changes needed and i will commit the code without any comments in the code base

**Comment by MeetDOD** [comment]
@manikumarreddyu Excellent Bro,

1. But in codesnippet can't see code in light mode.

image

3. Also you changed the delete button, bring the previous delete button.

New: 
image

Old:
image

**Comment by MeetDOD** [comment]
@manikumarreddyu Excellent Bro,

1. But in codesnippet can't see code in light mode.

image

2. Also you changed the delete button, bring the previous delete button back.

New: 
image

Old:
image

**Comment by manikumarreddyu** [comment]
> @manikumarreddyu Excellent Bro,
> 
> 1. But in codesnippet can't see code in light mode.
> 
> image
> 
> 2. Also you changed the delete button, bring the previous delete button back.
> 
> New: image
> 
> Old: image
> 
> 3. This also.
> 
> image
> 
> image

Thank you @MeetDOD  
1. i will correct the code for codesnippet
2. i will make change for delete button
3. for tages also

thank you for reporing errors in my code @MeetDOD

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
1. Don't use plain white for the light theme. it doesn't look good. You can use light blue instead.
2. There was bg image on the home page, maybe you can use that for dark mode
image
3. As @MeetDOD said, there are some places which are breaking when changing themes like the code section of post page
4. also the overall website looks darker than the actual website in dark mode. take reference from live website and keep things similar in dark mode

**Comment by manikumarreddyu** [comment]
sure @VaibhavArora314 . I am working on it and make it better

**Comment by manikumarreddyu** [comment]
> 1. Don't use plain white for the light theme. it doesn't look good. You can use light blue instead.
> 2. There was bg image on the home page, maybe you can use that for dark mode
>    image
> 3. As @MeetDOD said, there are some places which are breaking when changing themes like the code section of post page
> 4. also the overall website looks darker than the actual website in dark mode. take reference from live website and keep things similar in dark mode

1. can you prove me the hex code for that light blue..
2. i will set it up
3. all are completered as far as i know 
4.okay

**Comment by manikumarreddyu** [comment]
hey @VaibhavArora314  @MeetDOD check the latest deployment and suggest any changes

**Comment by MeetDOD** [comment]
@manikumarreddyu Great work, but 

1. The edit button is circular previously but now it's changed see

old:
image

new:
image

I think you did something wrong Read more button is not perfect now

image

2. Add tag button css, it's showing white.

image

on hover:

image

Hmm that's it other things are fine 👍

**Comment by manikumarreddyu** [comment]
> @manikumarreddyu Great work, but
> 
> 1. The edit button is circular previously but now it's changed see
> 
> old: image
> 
> new: image
> 
> I think you did something wrong Read more button is not perfect now
> 
> image
> 
> 2. Add tag button css, it's showing white.
> 
> image
> 
> on hover:
> 
> image
> 
> Hmm that's it other things are fine 👍

okay @MeetDOD

**Comment by manikumarreddyu** [comment]
> 3\. As @MeetDOD said, there are some places which are breaking when changing themes like the code section of post page

hey @MeetDOD 

As @MeetDOD said, there are some places which are breaking when changing themes like the code section of post page

what you said in the above ,is it resolved or still there..

**Comment by MeetDOD** [comment]
Resolved @manikumarreddyu

**Comment by manikumarreddyu** [comment]
> Resolved @manikumarreddyu

okay @MeetDOD

**Comment by manikumarreddyu** [comment]
hey @VaibhavArora314 check it once , suggest changes
i have use bg image . and i dont think so adding another light color is a good thing .
with bg image , it became so beautiful it is not looking plain

DONT MERGE THIS
IF YOU OKAY WITH IT , just update me , i will remove commented lines in the code make and i will pus agin the final code

**Comment by VaibhavArora314** [comment]
i suggest that you break the pr into 2-3 prs where each prs has mode functionality for some pages. this will make it easier for me to review and conflicts will be easier to handle

**Comment by manikumarreddyu** [comment]
I am raising new PR
hey @VaibhavArora314 dont merge any PR before merging my PR
It is my sincere request for this one time
please consider my request

**Pull request closed without merging**
