### PR TITLE
updated scroll progress bar with the seperate files

### LINKED ISSUE #434: [Feature Request] : ✨ Add a Page Scroll Progress Bar at the Top of Your Startup Webpage
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Explain feature request
Hey @jfmartinz ,
I have noticed a small issue that I believe could enhance the user experience. Currently, there is no Page Scroll Progress Bar at the Top of Your Startup Webpage , which makes navigation a bit cumbersome, especially when users need to return to the top of a lengthy page.
Though it may seem minor, the absence of this feature can impact the overall usability and performance of the website.

### Use Case

Explain your solution

343870881-7f17e9d3-41c5-4fb0-a558-caf334552764

### Benefits

@VaibhavArora314 
Could you please assign me this issue under gssoc'24 ?

GSSOC'24

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by TheNikhilRaj**
# Pull Request

✨ Add a Page Scroll Progress Bar at the Top of Your Startup Webpage

Hey @jfmartinz ,
I have noticed a small issue that I believe could enhance the user experience. Currently, there is no Page Scroll Progress Bar at the Top of Your Startup Webpage , which makes navigation a bit cumbersome, especially when users need to return to the top of a lengthy page.
Though it may seem minor, the absence of this feature can impact the overall usability and performance of the website.

### Related Issues
Fixes #434 

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Additional Notes

Footer

@Ultimateutkarsh11 @VaibhavArora314 @akbatra567 #434
**updated scroll progress bar with the seperate files**

### CODE REVIEW

**Comment by TheNikhilRaj** [comment]
Capture1

from my side it's working!!

**Comment by VaibhavArora314** [comment]
Create a component for it as I stated before. You have written css and vanilla js code and included them in index.html but you should create a component for it and import it accordingly in app.tsx or navbar.tsx.

**Comment by VaibhavArora314** [comment]
Also, don't delete package-lock.json simply revert any changes done to it.

**Comment by TheNikhilRaj** [comment]
> Create a component for it as I stated before. You have written css and vanilla js code and included them in index.html but you should create a component for it and import it accordingly in app.tsx or navbar.tsx.

i had make seperate of that of css and js.

**Comment by VaibhavArora314** [comment]
> > Create a component for it as I stated before. You have written css and vanilla js code and included them in index.html but you should create a component for it and import it accordingly in app.tsx or navbar.tsx.
> 
> i had make seperate of that of css and js.

You can do the following if you are having problem understanding it
1. Create a component for the progress bar
2. Write CSS using tailwind in the component itself
3. Write javascript logic in the component itself
4. Import that component in navbar.tsx or app.tsx as needed

**Comment by TheNikhilRaj** [comment]
> Create a component for it as I stated before. You have written css and vanilla js code and included them in index.html but you should create a component for it and import it accordingly in app.tsx or navbar.tsx.

i don't know to create component as you can do from your it wiil be beeter from my i have gave my 100% to making this

**Comment by VaibhavArora314** [comment]
Ok, this is not the right approach to implement this in a React project, closing the pull request.

**Comment by TheNikhilRaj** [comment]
@VaibhavArora314 for next time you have to mention for another people that another people can't face you issues!
no people have not extra time to solve there personal issues!!
Reminder!

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 for next time you have to mention for another people that another people can't face you issues! no people have not extra time to solve there personal issues!! Reminder!

This is a pretty obvious thing that when contributing to any React project you use modern practices like creating components and not writing CSS and vanilla js code and importing them in index.html as that was one of the purposes React was developed for. You can see all the issues and pull requests, I never stated this to anyone but all of them created components for their work and used modern practises.

**Comment by TheNikhilRaj** [comment]
> @VaibhavArora314 for next time you have to mention for another people that another people can't face you issues! no people have not extra time to solve there personal issues!! Reminder!

@VaibhavArora314 for next time keep Reminder!

**Pull request closed without merging**
