### PR TITLE
FIX: Make the post card clickable

### LINKED ISSUE #350: [UX Change] Make the Post Card Clickable
## UX Change Requested
* While we hover over the card it gives an impression that the whole card is clickable and when we try clicking it. It doesn't function that way. 

## Impact
* It gives a wrong impression to the user, making it hard for user to understand when using the application for the first time.
* Makes user do extra mouse moment to reach the `Read More` button.

## Screenshot: 
Screenshot 2024-07-01 at 10 43 27 PM

## Acceptance Criteria
* As a user when I hover on the Post Card, it should:
  * Retain the current hover effect
  * Is clickable and redirects the same way `Read More` works.
  
cc: @VaibhavArora314, Do have a look ? 
- If this looks good, it is open for anyone to pick.

### PR DESCRIPTION
**Pull request by Vaibhav-kesarwani**
# Pull Request Resolves [#350]

### Title
Make the postcard clickable.

### Description
When we hover over the card, it appears as though we can click anywhere on it, and clicking takes us straight to the read more page.

### Related Issues
Fixes #350 

### Changes Made
Make the postcard clickable

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)
[Screencast from 22-07-24 10:53:56 PM IST.webm](https://github.com/user-attachments/assets/dc149c86-cba5-4975-a9a9-855aa1c5e77b)

### Additional Notes
By submitting this pull request, I attest that I have complied with the applicable code of conduct and supplied the necessary screenshot for verification.

### CODE REVIEW

**Comment by Vaibhav-kesarwani** [comment]
@VaibhavArora314 @akbatra567 @Ultimateutkarsh11 Please check it and merge !

Thank You !

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
image
we can remove the read more button since the whole card is clickable now

**Comment by Vaibhav-kesarwani** [comment]
ok, sure!

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by Vaibhav-kesarwani** [comment]
Screenshot from 2024-07-23 11-26-46

Done

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Review by akbatra567 — APPROVED** [review]

**Pull request merged**
