### PR TITLE
Added Language..now it  is  changing for all the components

### PR DESCRIPTION
**Pull request by manikumarreddyu**
# Pull Request

### Title

Added Language..now it  is  changing for all the components 
except testmonial section 
it is to be done after #293 is merged..

MERGE THIS PR to avoid conflicts then..

### Description

Added Language..now it  is  changing for all the components

### Related Issues

fixes:  #281 

### Changes Made

many changes

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Additional Notes

Footer

### CODE REVIEW

**Comment by manikumarreddyu** [comment]
hey @VaibhavArora314 check it once , and in my view it is a level 3 issue...review the changes i have made ..
i hope you consider my request...and for testimonial section i will do in new issue..because..  #293 should be merged..
thank you

**Review by VaibhavArora314 — COMMENTED** [review]
wait for #293 to be completed, then implement for the testimonials section also in this pr

**Comment by manikumarreddyu** [comment]
> wait for #293 to be completed, then implement for the testimonials section also in this pr

okay

**Comment by manikumarreddyu** [comment]
hey @VaibhavArora314 for testimonials also it is completed , please check it once and let me know any changes needed
Thank you

**Comment by VaibhavArora314** [comment]
this looks good, how did you generate translations? chatgpt?

**Comment by MeetDOD** [comment]
@VaibhavArora314 It's very easy first just write the json in english and give it to chatgpt and give him all the language name you want to convert it will do it and just paste it, there is no need of google translator and all.

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by manikumarreddyu** [comment]
> this looks good, how did you generate translations? chatgpt?

No @VaibhavArora314  I did it using Google translate. I don't know whether chatgpt is translating or not. I thought that chatgpt doesn't know telugu, Urdu ,Tamil .so I did it using Google translate and all..it made me feel very hard to do this task..😐.. I regret not taking help from @MeetDOD ..I should have asked hime before doing this...feeling sad..now

**Comment by MeetDOD** [comment]
> > this looks good, how did you generate translations? chatgpt?
> 
> No @VaibhavArora314 I did it using Google translate. I don't know whether chatgpt is translating or not. I thought that chatgpt doesn't know telugu, Urdu ,Tamil .so I did it using Google translate and all..it made me feel very hard to do this task..😐.. I regret not taking help from @MeetDOD ..I should have asked hime before doing this...feeling sad..now

No problem, you did wonderfull job without gpt 👍

**Comment by manikumarreddyu** [comment]
Screenshot_2024-06-28-15-35-42-397_com android chrome
Screenshot_2024-06-28-15-36-37-676_com android chrome
I have done like these...giving website link to google translate and replacing English words in json with newly translated lines

**Comment by MeetDOD** [comment]
image

If you find problem try this way !

**Comment by manikumarreddyu** [comment]
> > > this looks good, how did you generate translations? chatgpt?
> > 
> > 
> > No @VaibhavArora314 I did it using Google translate. I don't know whether chatgpt is translating or not. I thought that chatgpt doesn't know telugu, Urdu ,Tamil .so I did it using Google translate and all..it made me feel very hard to do this task..😐.. I regret not taking help from @MeetDOD ..I should have asked hime before doing this...feeling sad..now
> 
> No problem, you did wonderfull job without gpt 👍

@MeetDOD now I am laughing at what I did... 😂😂

**Comment by MeetDOD** [comment]
> > > > this looks good, how did you generate translations? chatgpt?
> > > 
> > > 
> > > No @VaibhavArora314 I did it using Google translate. I don't know whether chatgpt is translating or not. I thought that chatgpt doesn't know telugu, Urdu ,Tamil .so I did it using Google translate and all..it made me feel very hard to do this task..😐.. I regret not taking help from @MeetDOD ..I should have asked hime before doing this...feeling sad..now
> > 
> > 
> > No problem, you did wonderfull job without gpt 👍
> 
> @MeetDOD now I am laughing at what I did... 😂😂

bruh 🗿

**Comment by manikumarreddyu** [comment]
Hats off to chat gpt...it learnt all languages in the world..

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
