### PR TITLE
feat: Updated Home Page UI successfully Issue 4

### LINKED ISSUE #4: Enhance Home page of the website
try not to modify the navbar and footer unnecessarily as merge conflicts may arise later.

image

There need to be added following 2 sections:
1. An about us section
2. Recent posts sections

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves[#4 ]

### Description

1.  Added hero Image with floating animation.
 
2. Styled the Explored button.
 
3. Added Emoji's.

4. Implemented nice background.

5. Responsive also.

### Related Issues
Fixes #4 

### Changes Made
Improvements in Home page UI

### Screenshots

image

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Comment by VaibhavArora314** [comment]
@MeetDOD This looks great, also implement the About Us section and recent Posts section (for now simply show the first 6 posts from the posts API) as stated in the issue.

**Comment by VaibhavArora314** [comment]
since you are also working on the pagination issue, after implementing the pagination use that API to fetch 1st page and pass page size of 6 for the recent posts case

**Comment by MeetDOD** [comment]
So, sir basically also i make to design for about us section so should I raise another issue and through that issue I should work on it. 
also sir what should i include in about us section like the conetent and all ?

**Comment by VaibhavArora314** [comment]
in about section just write what the project scope is and how it works etc

**Comment by MeetDOD** [comment]
Ok @VaibhavArora314 Got it :)

**Comment by MeetDOD** [comment]
@VaibhavArora314 Sir, how about this Approach, if you like it then i will implement it !

image

**Comment by VaibhavArora314** [comment]
That looks great, go ahead

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by VaibhavArora314** [comment]
Work continued in #78

**Pull request closed without merging**
