### PR TITLE
feat: Added admin login logic in backend successfully issue 343

### LINKED ISSUE #343: [Feature Request]: Creating the admin login in backend
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Creating an additional parameter in the user model for isAdmin which is false for all users by default in backend folder.

### Use Case

Admin flexibility.

### Benefits

Admin usage

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolve [#343 ]

### Description

1. In backend, In prisma at user add new field i.e isAdmin: bool, In routes created admin folder in that i created controllers for adminLogin and fetching admin profile with adminAuth middleware.
2. Created routes for both and created zodSchema for admin.
3. Api is tested in postman and in thunder client and is working fine.

### Related Issues
Fixes #343 

### Changes Made
New features: Added admin login logic in backend.

### Screenshots

image

image

image

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Comment by MeetDOD** [comment]
@VaibhavArora314 assign the necessary GGSOC labels #343 
I am creating this because i am not available tomorrow that's why i created the PR first without your permission.
So, please tell me if any changes needed respectively.
Thank You 😀

**Comment by MeetDOD** [comment]
@VaibhavArora314 Just explain me the approach of the code like how i code in the different folder admin/frontend because the code is ready without any issue just the folder approach is not cleared to me.

Please explain me.
Thank you 👍

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
everything looks good, just add verifyJwt logic since you are directly decoding it in admin auth middleware

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by MeetDOD** [comment]
@VaibhavArora314 Done 👍

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by MeetDOD** [comment]
@VaibhavArora314 I think it deserve level 3 if possible upon evaluation 😀

**Pull request merged**
