### PR TITLE
sinup_signin_relocated

### LINKED ISSUE #516: [Bug]: set signin and signup buttons on the right side of the appbar thus enhancing ui
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The signup and signin buttons should be on the right part of the navbar /appbar rather than on the left part

### Expected behavior

The signup and signin buttons should be on the right part of the navbar /appbar rather than on the left part enhancing UI

### Add ScreenShots

Screenshot 2024-07-27 165504

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by haseebzaki-07**
# Pull Request
fixes #516 

### Title
Relocated signIn and signUp buttons to the right side of the navbar

### Changes Made
changed the CSS of div containing the signIn and signUp buttons

### Checklist 
- [x ] I have tested the changes locally
- [x ] Documentation has been updated (if necessary)
- [x ] Changes are backward-compatible

### Screenshots (if applicable)
Screenshot 2024-07-28 162723

### CODE REVIEW

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
remove package-lock,json from the root of project

**Comment by haseebzaki-07** [comment]
I have removed package-lock.json from root of the project

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Review by VaibhavArora314 — APPROVED** [review]
Next time keep the code formatter off, it makes it difficult for us to identify changes

**Comment by haseebzaki-07** [comment]
okay noted!

**Review by akbatra567 — APPROVED** [review]

**Pull request merged**
