### PR TITLE
feat: Added Multilanguage feature in overall webapp successfully issue 149

### LINKED ISSUE #149: [Feature Request]: Muti Language support
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This feature enable user to switch between different languages, currently i am focusing to convert english to hindi but i will implement more languages as you suggest.

### Use Case

Any user can interact with the webapp without languagae barriers

### Benefits

Increase User Experience. 

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves[#149 ]

### Description

1.  With the help of npm packages => i18next and react-i18next, I implemented this feature.
2.  In this I created a i18n where all the init and language function is coded and imported in app.tsx.
3.  Then i create a navbar so user can choose between the various languagues, initially i implemented total top 7 Indian languages.
4.  I am storing the lan in localStorage also so that even when reload the page it remain as it is.
5.  All I fixed the dropdown so that it will appear in all the pages.
6.  I am not implementing it in the toast messages because they are comming from the backend and all.
7.  I had try to convert as many text as possible to different languages.

### Related Issues
Fixes #149 

### Changes Made
New features: Added Multilanguage feature in overall webapp.

### Screenshots

image

### Video

**NOTE: There is a problem in the video the dropdown is not showing. so, I added it in screenshots**

https://github.com/VaibhavArora314/StyleShare/assets/120380073/b3429179-87f2-4fa5-877d-56cbd70a61c8

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Comment by MeetDOD** [comment]
@VaibhavArora314 If you want more languages that just give me the names i will implement them.

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 If you want more languages that just give me the names i will implement them.

this much looks good, I will take some time to review it completely since there are so many changes

**Comment by MeetDOD** [comment]
Ya, the languages is coming from locales => en,hi,... => translation.json. aslo, should i resolve the conflicts ?

**Comment by MeetDOD** [comment]
Done @VaibhavArora314 also tell me if you want more languages 😄

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
