### PR TITLE
✔️Added MIT License in Footer

### LINKED ISSUE #538: ➕ Feature: Add a Dedicated Licensing Page Reflecting the "MIT Licence"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

hey @VaibhavArora314 @akbatra567 and @Ultimateutkarsh11 

To provide clear information about the licensing of the website's content and code, we need to add a dedicated "Licensing Page" that reflects the use of the MIT License.

**What will I do :**
1. **Create Licensing Page** 2. **Content for Licensing Page**
2.  Include a brief introduction explaining the importance of licensing.
     - Provide the full text of the MIT License.
3.  Will **Style the page to Follow the  theme of the website.**
4.  Will **Add "Licensing" in the Footer**, To **Navigate to this Separate Page** in Legal section.

for ex like this : 

image

please assign me this issue under gssoc'24

### Use Case

.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by aslams2020**
Hey @VaibhavArora314 , @akbatra567 and @Ultimateutkarsh11 
issue closes #538 

I have added the MIT License navigating link in the footer.

Please take a look - 
image

https://github.com/user-attachments/assets/cb19b20e-50f3-427c-a8ea-e1cee0512724

### Checklist 

- [ ] I have tested the changes locally
- [ ] Documentation has been updated (if necessary)
- [ ] Changes are backward-compatible

### Additional Notes

Footer

### CODE REVIEW

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
Also add a link to MIT License in the policy page of the application.

**Comment by aslams2020** [comment]
@VaibhavArora314 Exactly where i should add the link ? 
Actually i am not able to understand

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 Exactly where i should add the link ? 
> Actually i am not able to understand

The other links of the legal section of the footer lead to a policy page. In that page add a simple line saying that the mit license can be accessed here.

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by aslams2020** [comment]
@VaibhavArora314 Done! 
Please check


https://github.com/user-attachments/assets/80e2896b-4e76-40ef-b2af-765d3c951ccd

**Comment by aslams2020** [comment]
@Ultimateutkarsh11 @akbatra567

**Review by akbatra567 — APPROVED** [review]

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
