### PR TITLE
Added js tab in the code editor

### PR DESCRIPTION
**Pull request by Parth18Shah**
# Pull Request for Issue #264 

### Title
Added a tab in the code editor for the users to add javascript code to their work

### Description
Users can add javascript code in the code editor and view the changes in real-time. On sharing, the javascript code gets copied to the text area along with the HTML code snippet.

### Related Issues
N.A.

### Changes Made
Updated the code editor file and added tabs similar to what we have done in the posts section.

### Checklist 
- [x] I have tested the changes locally
- [ ] Documentation has been updated (if necessary)
- [ ] Changes are backward-compatible

### Screenshots (if applicable)
N.A.

### Additional Notes
N.A.

Footer

### CODE REVIEW

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
looks good, just make this responsive
image
image

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by Parth18Shah** [comment]
I have updated the code to make the buttons responsive

**Comment by VaibhavArora314** [comment]
image
resolve errors

**Comment by Parth18Shah** [comment]
Updated the code accordingly. Thanks for notifying me. Apologies for the delay.

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
