### PR TITLE
feat: Added Toast Notification to the whole webapp Successfully Issue 103

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [#103 ]

### Description

1.  Used react-hot-toast npm library throughout the app.
2.  First <Toaster /> is init in App.tsx.
3.  With toast.success/error the operation is performed.

### Related Issues
Fixes: #103 

### Changes Made
New feature: Added Toast Notification with react-hot-toast.

### Screenshots

image

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Comment by VaibhavArora314** [comment]
did you also push changes of the like/dislike functionality of your other PR

**Comment by MeetDOD** [comment]
No, i created two branch for both the issues #103 and #87 i don't know why it is showing commit's above ?

**Comment by MeetDOD** [comment]
Ya i think the above pr ha both the functinality toast + like/dislike .

**Comment by MeetDOD** [comment]
You can merge it without conflicts

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
resolve merge conflicts

**Comment by MeetDOD** [comment]
@VaibhavArora314  Done 👍

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
everything looks good, just one thing in the Profile, don't remove error message and verification error state logic

**Comment by MeetDOD** [comment]
@VaibhavArora314 finally it's done :)

**Pull request merged**
