### PR TITLE
Changed Language option button to responsive

### PR DESCRIPTION
**Pull request by manikumarreddyu**
# Pull Request

### Title

Changed Language option button to responsive

### Description

Changed Language option button to responsive

### Related Issues

Fixes: #208

### Changes Made

1. changed in navbar.tsx
2. app.tsx
3. languagedropdown.tsx

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)

image
image
image

### Additional Notes

nothing

### CODE REVIEW

**Comment by manikumarreddyu** [comment]
hey @VaibhavArora314 check it once , and let me know any changes required.
Thank you!!

**Comment by VaibhavArora314** [comment]
image

**Comment by manikumarreddyu** [comment]
Sure @VaibhavArora314

**Comment by manikumarreddyu** [comment]
hey @VaibhavArora314 check it once , and let me know any changes required.
Thank you!!

**Comment by VaibhavArora314** [comment]
image

**Comment by VaibhavArora314** [comment]
also if possible please restore the purple-blue variant of navbar, it looked better

**Comment by manikumarreddyu** [comment]
Sure @VaibhavArora314

**Comment by manikumarreddyu** [comment]
image

hey @VaibhavArora314 check it once , and let me know any changes required.
Thank you!!

**Comment by VaibhavArora314** [comment]
image

**Comment by manikumarreddyu** [comment]
Hey @VaibhavArora314  ..are seeing it in which I have deployed or any other..

My deployment is coming well

**Comment by manikumarreddyu** [comment]
image
image


hey @VaibhavArora314 check it once , and let me know any changes required.
Thank you!!

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
