### PR TITLE
feat: Navbar responsiveness fixed successfully Issue 205

### LINKED ISSUE #205: [Feature Request]: Making navbar responsive.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Nabar is not responsive in medium devices.

### Use Case

User experience

### Benefits

User interaction

### Add ScreenShots

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [#205 ]

### Description

1.  Instead of md device I shifted the responsiveness to lg devices in tailwind classes to achieve responsive design.

### Related Issues
Fixes #205 

### Changes Made
New features: Navbar responsiveness fixed.

### Screenshots

image

image

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
Remove the file-saver package and don't push changes of other pr. I can't merge this because of some changes needed in edit functionality.

**Comment by MeetDOD** [comment]
@VaibhavArora314 i am trying but when there is PR i cannot work on new feature git automatically push that also, i don't know why 😭

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 i am trying but when there is PR i cannot work on new feature git automatically push that also, i don't know why 😭

maybe when creating a new branch, create it from your main branch rather than the current working branch

**Comment by MeetDOD** [comment]
Ok i got it thanks

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
remove merge conflicts and maybe you can undo the changes of edit functionality in this pr because they are on an older version of your pr

**Comment by MeetDOD** [comment]
Ok @VaibhavArora314 i got it i will do the changes

**Comment by MeetDOD** [comment]
@VaibhavArora314 you can close this and merge this pr => #225

**Pull request closed without merging**
