### PR TITLE
Feat: Added Fetched and created separate page for comments for admin successfully Issue 440

### LINKED ISSUE #440: [Feature Request]: Fetching and creating separate page for comments for admin
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Like manage user, manage contact messages and manage posts, similarly I will create a page for comment so that admin can read and also delete the comment if the comments are spam, malicious or self-promotions etc...

### Use Case

Admin flexibility.

### Benefits

UI/UX

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MeetDOD**
# Pull Request Resolves [#440 ]

### Description

1. In backend, created API controoler for comment deletion and similarly routes also.
2. In frontend, created a new file for comment section where I am fetching the posts with its comments and also adding delete button so, that admin can delete the spam comment.
3. The design is responsive. 

### Related Issues
Fixes #440 

### Changes Made
New feature: Added Fetched and created separate page for comments for admin.

### Screenshots

image

Screenshot 2024-07-17 183424

I certify that I have carried out the relevant code of conduct and provided the requisite screenshot for validation by submitting this pull request.

Thank You for this contribution.

### CODE REVIEW

**Comment by MeetDOD** [comment]
@VaibhavArora314 @Ultimateutkarsh11  there are many comments in the style share right now, but it is not fetching at all I don't want is the problem ?
In status card also:

image

In comment which i currently worked in this pr:

image

I don't know what is wrong is going on !

**Comment by MeetDOD** [comment]
> @VaibhavArora314 @Ultimateutkarsh11 there are many comments in the style share right now, but it is not fetching at all I don't know is the problem ? In status card also:
> 
> image
> 
> In comment which i currently worked in this pr:
> 
> image
> 
> I don't know what is wrong is going on !

**Comment by MeetDOD** [comment]
@VaibhavArora314 @Ultimateutkarsh11  there are many comments in the style share right now, but it is not fetching at all I don't know is the problem ?
In status card also:

image

In comment which i currently worked in this pr:

image

I don't know what is wrong is going on !

**Review by VaibhavArora314 — APPROVED** [review]

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Review by akbatra567 — APPROVED** [review]

**Comment by MeetDOD** [comment]
@VaibhavArora314 Bruh level 2 ? see all the code please

**Comment by MeetDOD** [comment]
Frontend + backend integration and UI also please give level 3 🙏

**Comment by MeetDOD** [comment]
@Ultimateutkarsh11 !

**Pull request merged**
