### PR TITLE
Added OTP verification for signup

### LINKED ISSUE #9: No verification of user's email via OTP
When user signs up, there is no verification being done whether the email is their's or not. 
We need to send a OTP to the user for this.

https://github.com/VaibhavArora314/StyleShare/assets/143820879/86e5b634-5069-4819-884c-2116dfb3f4b8

Obviously, no such email as the one entered here exists as the one entered above.

### PR DESCRIPTION
**Pull request by Joyosmit**
# What does it fix?
Fixes #9 . When signing up users get a OTP which they need to enter for verification.

# What features does it add?
1. It is implemented using nodemailer.
2. If OTP verification is not done, user cannot sign in. 
3. If user tries to sign in without verifying, user is prompted to do OTP verification first.
4. OTP is valid for 10 minutes.

# Screen recording for normal sign up flow:

https://github.com/VaibhavArora314/StyleShare/assets/143820879/27243406-e12d-463b-8f43-c70e5883b688

### CODE REVIEW

**Comment by VaibhavArora314** [comment]
this looks good but since there are so many changes, I will take some time to review it

**Comment by VaibhavArora314** [comment]
Hey so upon closer inspection I found that we are sending the jwt token on the user sign-up route and updating it in the recoil state after verifying the user but this has a security loophole as the user can inspect the frontend application and get the jwt token without verifying the email id and use it further. 

So I suggest that we should send the jwt token in the verify route itself and not in the sign-up route in the backend.

**Comment by Joyosmit** [comment]
Alright. I'll make that change.

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by Joyosmit** [comment]
For this to work, you need to have -
1. EMAIL_USER = <youremail@gmail.com>
2. EMAIL_PASS = <16character app password>
To get app password, first enable 2 step-verification on your google account, then set a app password(it will be of 16 characters).

Also pls the the GSSoC and Level 3 labels.

**Pull request merged**
