### PR TITLE
Scroll-to-top animation added

### LINKED ISSUE #262: [Feature Request]: Add animation to scroll to top button
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

 Add floating to and down animation to scroll to top button

### Use Case

 Add floating to and down animation to scroll to top button

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by poseidonsanket**
# Pull Request

### Title
Add animation to scroll to top button

### Description
Add floating to and down animation to scroll to top button

### Related Issues
Fixes #262 

### Changes Made
Added a custom css file to styles and added those css class names to scroll to top button.

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Additional Notes

Footer

### CODE REVIEW

**Comment by poseidonsanket** [comment]
@VaibhavArora314 please check my pull request

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
looks good to me just slower the animation(around 1.5-2s) and reduce the distance(use 12-15px instead of 20px in animation)

**Comment by poseidonsanket** [comment]
@VaibhavArora314 changed animation to 1.7s and distance to 15px please check

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
remove package-lock.json from root of repo

**Comment by poseidonsanket** [comment]
@VaibhavArora314 done

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
