### PR TITLE
fixed the slider buttons in light mode

### PR DESCRIPTION
**Pull request by manikumarreddyu**
# Pull Request

### Title

fixed the slider buttons in light mode
### Description

fixed the slider buttons in light mode
### Related Issues

Fixes: #293 

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)

image

### Additional Notes

thats it

Footer

### CODE REVIEW

**Comment by manikumarreddyu** [comment]
hey @VaibhavArora314 please check it once

**Comment by manikumarreddyu** [comment]
> remove package lock from root

thanks @VaibhavArora314 for seeing it...i removed it

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by manikumarreddyu** [comment]
hey @VaibhavArora314 please check it once
if merge this , i will do work on another PR because that PR is dependent on this one..

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
you have removed the sliding animation from the testimonials sections
also, it is not automatically changing after a few seconds

**Comment by manikumarreddyu** [comment]
> you have removed the sliding animation from the testimonials sections also, it is not automatically changing after a few seconds

previously i have used npm library ..it it doesnot have any options to change the ui of the buttons ..
in this version i have implemented slider from scratch and forget to add automatic scrolling ..thanks for reporting.. @VaibhavArora314 
i will implement it and update you and moreover , in my my view it is not a level 1 issue anymore as iam implementing it manually for having every feature we want..review my code and changes once and give label as per my work.
Thank you

**Comment by VaibhavArora314** [comment]
> > you have removed the sliding animation from the testimonials sections also, it is not automatically changing after a few seconds
> 
> previously i have used npm library ..it it doesnot have any options to change the ui of the buttons .. in this version i have implemented slider from scratch and forget to add automatic scrolling ..thanks for reporting.. @VaibhavArora314 i will implement it and update you and moreover , in my my view it is not a level 1 issue anymore as iam implementing it manually for having every feature we want..review my code and changes once and give label as per my work. Thank you

yes, I will update it to level 2. go ahead and implement the animation.

**Comment by manikumarreddyu** [comment]
> > > you have removed the sliding animation from the testimonials sections also, it is not automatically changing after a few seconds
> > 
> > 
> > previously i have used npm library ..it it doesnot have any options to change the ui of the buttons .. in this version i have implemented slider from scratch and forget to add automatic scrolling ..thanks for reporting.. @VaibhavArora314 i will implement it and update you and moreover , in my my view it is not a level 1 issue anymore as iam implementing it manually for having every feature we want..review my code and changes once and give label as per my work. Thank you
> 
> yes, I will update it to level 2. go ahead and implement the animation.

3 new things are added @VaibhavArora314 
1. animation
2. dots
3. when clicked om dots it goes to particular testimonial

**Comment by Ultimateutkarsh11** [comment]
@manikumarreddyu kindly resolve the merge conflicts

**Comment by manikumarreddyu** [comment]
> @manikumarreddyu kindly resolve the merge conflicts

resolved successfully

**Comment by manikumarreddyu** [comment]
hey @Ultimateutkarsh11 please check it once

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
